use std::collections::{BTreeMap, HashMap};
use std::env;
use std::fs::{self, File};
use std::io::{BufRead, BufReader, Write};
use std::path::{Path, PathBuf};
use std::time::Instant;

use anyhow::{Context, Result};
use chrono::{DateTime, Local, Utc};
use clap::{Parser, ValueEnum};
use memchr::memmem;
use rayon::prelude::*;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use walkdir::WalkDir;

#[derive(Debug, Parser)]
#[command(name = "gh-usage")]
#[command(
    about = "Scan local GitHub Copilot / VS Code Chat usage records and export credit usage as CSV",
    version
)]
struct Cli {
    /// VS Code workspaceStorage root. Defaults to the standard VS Code user-data path for the current OS.
    #[arg(long)]
    vscode_workspace_storage: Option<PathBuf>,

    /// Copilot CLI root. Reserved for optional probing; defaults to ~/.copilot.
    #[arg(long)]
    copilot_cli_root: Option<PathBuf>,

    /// Include generic Copilot CLI log probing. Slower and currently best-effort.
    #[arg(long)]
    include_cli_logs: bool,

    /// Only scan files modified within N days.
    #[arg(long)]
    since_days: Option<u64>,

    /// Maximum files to scan, useful while experimenting.
    #[arg(long)]
    max_files: Option<usize>,

    /// Output CSV path. Use '-' for stdout. Defaults to copilot-usage-<hostname>.csv beside the binary's working directory.
    #[arg(long, short)]
    output: Option<PathBuf>,

    /// Output format. CSV is the default for spreadsheet inspection.
    #[arg(long, value_enum, default_value_t = OutputFormat::Csv)]
    format: OutputFormat,

    /// Override the machine hostname embedded into records. Defaults to the detected OS hostname.
    #[arg(long)]
    hostname: Option<String>,

    /// Explicit path for the HTML summary report. Implies HTML output. Defaults to copilot-usage-<hostname>.html beside the CSV.
    #[arg(long)]
    html: Option<PathBuf>,

    /// Skip writing the HTML summary report. HTML is generated by default whenever a file output is produced.
    #[arg(long)]
    no_html: bool,

    /// Print a short summary to stderr after writing output.
    #[arg(long)]
    summary: bool,

    /// Do not write a UTF-8 BOM for file output. By default files include BOM for Windows Excel compatibility.
    #[arg(long)]
    no_bom: bool,

    /// Merge mode. Read every `copilot-usage-*.csv` in DIR (or the current directory when DIR is omitted)
    /// and render a combined `copilot-usage-merged.html` next to those CSVs. Skips the local VS Code scan.
    #[arg(long, value_name = "DIR", num_args = 0..=1, default_missing_value = ".")]
    merge: Option<PathBuf>,
}

#[derive(Debug, Clone, Copy, ValueEnum)]
enum OutputFormat {
    Csv,
    Json,
}

#[derive(Debug, Clone, Default)]
struct ContextFields {
    session_id: Option<String>,
    request_id: Option<String>,
    response_id: Option<String>,
    model_id: Option<String>,
    agent_id: Option<String>,
    timestamp_ms: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct UsageRecord {
    #[serde(default)]
    source: String,
    #[serde(default)]
    hostname: String,
    #[serde(default)]
    timestamp_ms: Option<i64>,
    #[serde(default)]
    local_time_hint: Option<String>,
    #[serde(default)]
    chat_title: Option<String>,
    #[serde(default)]
    model: String,
    #[serde(default)]
    model_id: Option<String>,
    #[serde(default)]
    credits: f64,
    #[serde(default)]
    details: String,
    #[serde(default)]
    session_id: Option<String>,
    #[serde(default)]
    request_id: Option<String>,
    #[serde(default)]
    response_id: Option<String>,
    #[serde(default)]
    agent_id: Option<String>,
    #[serde(default)]
    file: String,
    #[serde(default)]
    line: usize,
}

#[derive(Debug, Default)]
struct ScanStats {
    scanned_files: usize,
    scanned_lines: usize,
    json_candidate_lines: usize,
    parse_errors: usize,
}

#[derive(Debug, Default)]
struct FileScanResult {
    records: Vec<UsageRecord>,
    scanned_lines: usize,
    json_candidate_lines: usize,
    parse_errors: usize,
}

#[derive(Debug, Default)]
struct LineExtraction {
    response_metadata: HashMap<String, ContextFields>,
    records: Vec<RawUsageRecord>,
}

#[derive(Debug)]
struct RawUsageRecord {
    context: ContextFields,
    model: String,
    credits: f64,
    details: String,
}

fn main() -> Result<()> {
    let total_started = Instant::now();
    let no_args = env::args_os().len() == 1;
    let double_clicked = no_args && launched_from_explorer();
    let cli = Cli::parse();

    if let Some(dir) = cli.merge.clone() {
        return run_merge(&dir, double_clicked);
    }

    let hostname = cli
        .hostname
        .clone()
        .map(|name| sanitize_hostname(&name))
        .unwrap_or_else(detect_hostname);

    let output_path = cli
        .output
        .clone()
        .unwrap_or_else(|| default_output_path(&hostname, cli.format));

    let html_path = if cli.no_html {
        None
    } else if let Some(path) = cli.html.clone() {
        Some(path)
    } else if output_path.as_os_str() == "-" {
        None
    } else {
        Some(default_html_path(&output_path, &hostname))
    };

    let vscode_root = cli
        .vscode_workspace_storage
        .or_else(default_vscode_workspace_storage)
        .context(
            "Could not determine VS Code workspaceStorage path; pass --vscode-workspace-storage",
        )?;

    let copilot_cli_root = cli.copilot_cli_root.or_else(default_copilot_cli_root);
    let cutoff = cli.since_days.map(cutoff_system_time);

    let discover_started = Instant::now();
    let mut files = collect_vscode_chat_session_files(&vscode_root, cutoff.as_ref())?;

    if cli.include_cli_logs {
        if let Some(root) = copilot_cli_root.as_ref() {
            files.extend(collect_cli_probe_files(root, cutoff.as_ref())?);
        }
    }

    files.sort();
    files.dedup();

    if let Some(max_files) = cli.max_files {
        files.truncate(max_files);
    }
    let discover_ms = discover_started.elapsed().as_millis();

    let scanned_files = files.len();
    let scan_started = Instant::now();
    let file_results: Vec<FileScanResult> = files.par_iter().map(|path| scan_file(path)).collect();
    let scan_ms = scan_started.elapsed().as_millis();

    let reduce_started = Instant::now();
    let mut stats = ScanStats {
        scanned_files,
        ..ScanStats::default()
    };
    let mut records = Vec::new();

    for result in file_results {
        stats.scanned_lines += result.scanned_lines;
        stats.json_candidate_lines += result.json_candidate_lines;
        stats.parse_errors += result.parse_errors;
        records.extend(result.records);
    }

    records.sort_by(|a, b| {
        a.timestamp_ms
            .cmp(&b.timestamp_ms)
            .then_with(|| a.file.cmp(&b.file))
            .then_with(|| a.line.cmp(&b.line))
            .then_with(|| a.response_id.cmp(&b.response_id))
    });
    records.dedup_by(|a, b| {
        a.file == b.file
            && a.line == b.line
            && a.response_id == b.response_id
            && a.details == b.details
    });
    for record in &mut records {
        record.hostname = hostname.clone();
    }
    let reduce_ms = reduce_started.elapsed().as_millis();

    let write_started = Instant::now();
    match cli.format {
        OutputFormat::Csv => write_csv(&output_path, &records, !cli.no_bom)?,
        OutputFormat::Json => write_json(&output_path, &records, !cli.no_bom)?,
    }
    if let Some(html_path) = html_path.as_ref() {
        write_html(html_path, &records, &hostname)?;
    }
    let write_ms = write_started.elapsed().as_millis();
    let total_ms = total_started.elapsed().as_millis();

    if no_args || cli.summary {
        let report = build_summary_report(
            &output_path,
            html_path.as_deref(),
            &records,
            &stats,
            discover_ms,
            scan_ms,
            reduce_ms,
            write_ms,
            total_ms,
        );
        if output_path.as_os_str() == "-" {
            eprint!("{report}");
        } else {
            print!("{report}");
        }
    }

    if double_clicked {
        show_double_click_exit_notice(&output_path, html_path.as_deref());
    }

    Ok(())
}

fn show_double_click_exit_notice(output: &Path, html: Option<&Path>) {
    println!();
    println!(
        "CSV saved to {}",
        output.display()
    );
    println!(
        "  Every parsed Copilot usage record is in there - import it into Excel,"
    );
    println!(
        "  Power BI, or pipe it through your own scripts for deeper analysis."
    );
    if let Some(html) = html {
        println!();
        println!("HTML report saved to {}", html.display());
        println!(
            "  A self-contained, offline-friendly page with charts, host/model"
        );
        println!(
            "  filters, and a paginated record table. Safe to email or archive."
        );
        println!();
        println!(">> Press any key to open the HTML report in your default browser.");
        println!("   (Or close this window to skip - both files are already on disk.)");
        wait_for_any_key();
        open_path(html);
    } else {
        println!();
        println!("HTML report skipped (--no-html). The CSV above is your full dataset.");
        println!();
        println!(">> Press any key to close this window. The CSV is already saved.");
        wait_for_any_key();
    }
}

#[cfg(windows)]
fn open_path(path: &Path) {
    // `explorer.exe <path>` resolves files via the default shell handler
    // (HTML → default browser), without blocking us on the launched process.
    let _ = std::process::Command::new("explorer.exe").arg(path).spawn();
}

#[cfg(not(windows))]
fn open_path(_path: &Path) {}

#[cfg(windows)]
fn launched_from_explorer() -> bool {
    windows_parent_process_name()
        .as_deref()
        .is_some_and(|name| name.eq_ignore_ascii_case("explorer.exe"))
}

#[cfg(not(windows))]
fn launched_from_explorer() -> bool {
    false
}

#[cfg(windows)]
fn wait_for_any_key() {
    use windows_sys::Win32::Foundation::INVALID_HANDLE_VALUE;
    use windows_sys::Win32::System::Console::{
        GetConsoleMode, GetStdHandle, ReadConsoleW, SetConsoleMode, ENABLE_ECHO_INPUT,
        ENABLE_LINE_INPUT, STD_INPUT_HANDLE,
    };

    unsafe {
        let handle = GetStdHandle(STD_INPUT_HANDLE);
        if handle == INVALID_HANDLE_VALUE {
            return;
        }

        let mut original_mode = 0;
        if GetConsoleMode(handle, &mut original_mode) == 0 {
            let mut input = String::new();
            let _ = std::io::stdin().read_line(&mut input);
            return;
        }

        let single_key_mode = original_mode & !(ENABLE_LINE_INPUT | ENABLE_ECHO_INPUT);
        let _ = SetConsoleMode(handle, single_key_mode);

        let mut buffer = [0u16; 1];
        let mut chars_read = 0;
        let _ = ReadConsoleW(
            handle,
            buffer.as_mut_ptr().cast(),
            buffer.len() as u32,
            &mut chars_read,
            std::ptr::null_mut(),
        );

        let _ = SetConsoleMode(handle, original_mode);
    }
}

#[cfg(not(windows))]
fn wait_for_any_key() {}

#[cfg(windows)]
fn windows_parent_process_name() -> Option<String> {
    use windows_sys::Win32::Foundation::{CloseHandle, INVALID_HANDLE_VALUE};
    use windows_sys::Win32::System::Diagnostics::ToolHelp::{
        CreateToolhelp32Snapshot, Process32FirstW, Process32NextW, PROCESSENTRY32W,
        TH32CS_SNAPPROCESS,
    };

    unsafe {
        let snapshot = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
        if snapshot == INVALID_HANDLE_VALUE {
            return None;
        }

        let mut entry = std::mem::zeroed::<PROCESSENTRY32W>();
        entry.dwSize = std::mem::size_of::<PROCESSENTRY32W>() as u32;

        let current_pid = std::process::id();
        let mut parent_pid = None;

        if Process32FirstW(snapshot, &mut entry) != 0 {
            loop {
                if entry.th32ProcessID == current_pid {
                    parent_pid = Some(entry.th32ParentProcessID);
                    break;
                }

                if Process32NextW(snapshot, &mut entry) == 0 {
                    break;
                }
            }
        }

        let Some(parent_pid) = parent_pid else {
            let _ = CloseHandle(snapshot);
            return None;
        };

        if Process32FirstW(snapshot, &mut entry) != 0 {
            loop {
                if entry.th32ProcessID == parent_pid {
                    let name = wide_process_name_to_string(&entry.szExeFile);
                    let _ = CloseHandle(snapshot);
                    return name;
                }

                if Process32NextW(snapshot, &mut entry) == 0 {
                    break;
                }
            }
        }

        let _ = CloseHandle(snapshot);
        None
    }
}

#[cfg(windows)]
fn wide_process_name_to_string(buffer: &[u16]) -> Option<String> {
    let len = buffer.iter().position(|ch| *ch == 0).unwrap_or(buffer.len());
    if len == 0 {
        None
    } else {
        Some(String::from_utf16_lossy(&buffer[..len]))
    }
}

/// Merge mode: read every `copilot-usage-*.csv` in `dir`, combine + dedupe,
/// render a single `copilot-usage-merged.html` next to those CSVs.
fn run_merge(dir: &Path, double_clicked: bool) -> Result<()> {
    if !dir.is_dir() {
        anyhow::bail!(
            "merge target is not a directory: {}",
            dir.display()
        );
    }

    let mut csv_files: Vec<PathBuf> = Vec::new();
    for entry in fs::read_dir(dir)
        .with_context(|| format!("read_dir failed for {}", dir.display()))?
    {
        let entry = entry?;
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        let name = match path.file_name().and_then(|s| s.to_str()) {
            Some(n) => n,
            None => continue,
        };
        let lower = name.to_ascii_lowercase();
        if !lower.starts_with("copilot-usage-") || !lower.ends_with(".csv") {
            continue;
        }
        // Skip our own merged outputs so re-running is idempotent.
        if lower == "copilot-usage-merged.csv" {
            continue;
        }
        csv_files.push(path);
    }
    csv_files.sort();

    if csv_files.is_empty() {
        anyhow::bail!(
            "no copilot-usage-*.csv files found in {}",
            dir.display()
        );
    }

    let mut records: Vec<UsageRecord> = Vec::new();
    let mut per_file: Vec<(PathBuf, usize)> = Vec::new();
    let mut row_errors: usize = 0;
    for path in &csv_files {
        let before = records.len();
        let mut reader = csv::ReaderBuilder::new()
            .flexible(true)
            .from_path(path)
            .with_context(|| format!("open csv {}", path.display()))?;
        for row in reader.deserialize::<UsageRecord>() {
            match row {
                Ok(record) => records.push(record),
                Err(_) => row_errors += 1,
            }
        }
        per_file.push((path.clone(), records.len() - before));
    }

    // Backfill hostname for legacy CSVs (pre-hostname column) using the file stem.
    for (path, _) in &per_file {
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_default();
        if let Some(host_from_name) = stem.strip_prefix("copilot-usage-") {
            for record in records.iter_mut().filter(|r| r.hostname.is_empty()) {
                record.hostname = host_from_name.to_owned();
            }
        }
    }

    records.sort_by(|a, b| {
        a.hostname
            .cmp(&b.hostname)
            .then_with(|| a.timestamp_ms.cmp(&b.timestamp_ms))
            .then_with(|| a.file.cmp(&b.file))
            .then_with(|| a.line.cmp(&b.line))
            .then_with(|| a.response_id.cmp(&b.response_id))
    });
    records.dedup_by(|a, b| {
        a.hostname == b.hostname
            && a.file == b.file
            && a.line == b.line
            && a.response_id == b.response_id
            && a.details == b.details
    });

    let hosts: std::collections::BTreeSet<String> =
        records.iter().map(|r| r.hostname.clone()).collect();
    let primary_host = hosts
        .iter()
        .next()
        .cloned()
        .unwrap_or_else(|| "merged".to_owned());

    let html_path = dir.join("copilot-usage-merged.html");
    write_html(&html_path, &records, &primary_host)?;

    // Compact merge summary, mirroring the look of the regular scan report.
    const INNER: usize = 54;
    let row = |content: String| -> String {
        let len = content.chars().count();
        let padded = if len < INNER {
            format!("{content}{}", " ".repeat(INNER - len))
        } else {
            content.chars().take(INNER).collect()
        };
        format!("| {padded} |\n")
    };
    let header = |title: &str| -> String {
        let prefix = format!("- {title} ");
        let pad = (INNER + 2).saturating_sub(prefix.chars().count());
        format!("+{prefix}{}+\n", "-".repeat(pad))
    };
    let plain_border = || -> String { format!("+{}+\n", "-".repeat(INNER + 2)) };

    let total_credits = normalize_zero(records.iter().map(|r| r.credits).sum());
    let host_list: Vec<&str> = hosts.iter().map(String::as_str).collect();

    let mut out = String::new();
    out.push_str(&header("GitHub Copilot Usage - Merge"));
    out.push_str(&row(format!(
        "{:<14}{:>12}  {:<14}{:>12}",
        "csv files",
        csv_files.len(),
        "row errors",
        row_errors
    )));
    out.push_str(&row(format!(
        "{:<14}{:>12}  {:<14}{:>12}",
        "records",
        records.len(),
        "hosts",
        hosts.len()
    )));
    out.push_str(&row(format!(
        "{:<14}{:>12}  {:<14}{:>12}",
        "total credits",
        format!("{:.1}", total_credits),
        "target dir",
        clip(&dir.display().to_string(), 12)
    )));

    out.push_str(&header("Sources"));
    for (path, count) in &per_file {
        let file_name = path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or("<unknown>");
        out.push_str(&row(format!(
            "{:<40}{:>14}",
            clip(file_name, 40),
            format!("{count} rows")
        )));
    }

    out.push_str(&header("Hosts"));
    out.push_str(&row(clip(&host_list.join(", "), INNER)));

    out.push_str(&header("Output"));
    out.push_str(&row(format!(
        "html  {}",
        clip(&html_path.display().to_string(), INNER - 6)
    )));
    out.push_str(&plain_border());
    print!("{out}");

    if double_clicked {
        show_merge_exit_notice(&html_path, &host_list);
    }
    Ok(())
}

fn show_merge_exit_notice(html: &Path, hosts: &[&str]) {
    println!();
    println!("Merged HTML report saved to {}", html.display());
    println!(
        "  Combined data from {} machine(s): {}",
        hosts.len(),
        hosts.join(", ")
    );
    println!(
        "  Open it in any browser - charts, filters, and pagination work offline,"
    );
    println!(
        "  and the single file is safe to email or archive."
    );
    println!();
    println!(">> Press any key to open the merged report in your default browser.");
    println!("   (Or close this window to skip - the HTML is already on disk.)");
    wait_for_any_key();
    open_path(html);
}

fn build_summary_report(
    output: &Path,
    html: Option<&Path>,
    records: &[UsageRecord],
    stats: &ScanStats,
    _discover_ms: u128,
    _scan_ms: u128,
    _reduce_ms: u128,
    _write_ms: u128,
    total_ms: u128,
) -> String {
    let total_credits = normalize_zero(records.iter().map(|record| record.credits).sum());
    let mut daily: BTreeMap<String, (usize, f64)> = BTreeMap::new();

    for record in records {
        let day = record
            .timestamp_ms
            .and_then(format_local_day)
            .unwrap_or_else(|| "unknown-date".to_owned());
        let entry = daily.entry(day).or_default();
        entry.0 += 1;
        entry.1 += record.credits;
    }

    let active_days = daily
        .keys()
        .filter(|day| day.as_str() != "unknown-date")
        .count();
    let average_per_active_day = if active_days > 0 {
        normalize_zero(total_credits / active_days as f64)
    } else {
        0.0
    };

    // Layout: outer width 58, inner content width 54.
    const INNER: usize = 54;
    let row = |content: String| -> String {
        let len = content.chars().count();
        let padded = if len < INNER {
            format!("{content}{}", " ".repeat(INNER - len))
        } else {
            content.chars().take(INNER).collect()
        };
        format!("| {padded} |\n")
    };
    let header = |title: &str| -> String {
        // Inner dashed span between the two `+` corners must equal INNER + 2.
        let prefix = format!("- {title} ");
        let pad = (INNER + 2).saturating_sub(prefix.chars().count());
        format!("+{prefix}{}+\n", "-".repeat(pad))
    };
    let plain_border = || -> String { format!("+{}+\n", "-".repeat(INNER + 2)) };

    let kv2 = |lk: &str, lv: String, rk: &str, rv: String| -> String {
        // 14 label + 12 value + 2 sep + 14 label + 12 value = 54
        row(format!(
            "{:<14}{:>12}  {:<14}{:>12}",
            lk, lv, rk, rv
        ))
    };

    let mut report = String::new();
    report.push_str(&header("GitHub Copilot Usage"));
    report.push_str(&kv2(
        "records",
        records.len().to_string(),
        "scanned files",
        stats.scanned_files.to_string(),
    ));
    report.push_str(&kv2(
        "total credits",
        format!("{:.1}", total_credits),
        "candidate lines",
        stats.json_candidate_lines.to_string(),
    ));
    report.push_str(&kv2(
        "active days",
        active_days.to_string(),
        "parse errors",
        stats.parse_errors.to_string(),
    ));
    report.push_str(&kv2(
        "avg / day",
        format!("{:.1}", average_per_active_day),
        "total time",
        format!("{:.2} s", total_ms as f64 / 1000.0),
    ));

    if !daily.is_empty() {
        report.push_str(&header("Daily credits"));
        for (day, (count, credits)) in &daily {
            // 12 date + 6 records right + 11 " records   " + 12 credits right + 13 " credits   " = 54
            report.push_str(&row(format!(
                "{:<12}{:>5} records   {:>10.2} credits     ",
                day, count, credits
            )));
        }
    }

    report.push_str(&header("Files"));
    report.push_str(&row(format!("csv   {}", clip(&output.display().to_string(), INNER - 6))));
    if let Some(html) = html {
        report.push_str(&row(format!("html  {}", clip(&html.display().to_string(), INNER - 6))));
    } else {
        report.push_str(&row("html  (disabled via --no-html)".to_owned()));
    }
    report.push_str(&plain_border());
    report
}

fn clip(s: &str, max: usize) -> String {
    let count = s.chars().count();
    if count <= max {
        return s.to_owned();
    }
    // Keep tail (filename) visible; replace head with "…".
    let skip = count - (max - 1);
    let mut out = String::from("…");
    out.extend(s.chars().skip(skip));
    out
}

fn default_vscode_workspace_storage() -> Option<PathBuf> {
    let candidates = vscode_workspace_storage_candidates();

    candidates
        .iter()
        .find(|path| path.exists())
        .cloned()
        .or_else(|| candidates.into_iter().next())
}

fn vscode_workspace_storage_candidates() -> Vec<PathBuf> {
    vscode_user_data_dirs()
        .into_iter()
        .map(|path| path.join("User").join("workspaceStorage"))
        .collect()
}

#[cfg(windows)]
fn vscode_user_data_dirs() -> Vec<PathBuf> {
    env::var_os("APPDATA")
        .map(PathBuf::from)
        .map(|path| vec![path.join("Code"), path.join("Code - Insiders")])
        .unwrap_or_default()
}

#[cfg(target_os = "macos")]
fn vscode_user_data_dirs() -> Vec<PathBuf> {
    home_dir()
        .map(|home| {
            let application_support = home.join("Library").join("Application Support");
            vec![
                application_support.join("Code"),
                application_support.join("Code - Insiders"),
            ]
        })
        .unwrap_or_default()
}

#[cfg(all(unix, not(target_os = "macos")))]
fn vscode_user_data_dirs() -> Vec<PathBuf> {
    let config_home = env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .or_else(|| home_dir().map(|home| home.join(".config")));

    config_home
        .map(|path| vec![path.join("Code"), path.join("Code - Insiders")])
        .unwrap_or_default()
}

fn normalize_zero(value: f64) -> f64 {
    if value.abs() < f64::EPSILON {
        0.0
    } else {
        value
    }
}

fn default_copilot_cli_root() -> Option<PathBuf> {
    home_dir().map(|path| path.join(".copilot"))
}

fn home_dir() -> Option<PathBuf> {
    env::var_os("HOME")
        .or_else(|| env::var_os("USERPROFILE"))
        .map(PathBuf::from)
}

fn cutoff_system_time(days: u64) -> std::time::SystemTime {
    std::time::SystemTime::now() - std::time::Duration::from_secs(days.saturating_mul(24 * 60 * 60))
}

fn collect_vscode_chat_session_files(
    root: &Path,
    cutoff: Option<&std::time::SystemTime>,
) -> Result<Vec<PathBuf>> {
    if !root.exists() {
        return Ok(Vec::new());
    }

    let mut files = Vec::new();
    for workspace_entry in fs::read_dir(root)? {
        let Ok(workspace_entry) = workspace_entry else {
            continue;
        };
        let Ok(file_type) = workspace_entry.file_type() else {
            continue;
        };
        if !file_type.is_dir() {
            continue;
        }

        let chat_sessions = workspace_entry.path().join("chatSessions");
        let Ok(session_entries) = fs::read_dir(chat_sessions) else {
            continue;
        };

        for session_entry in session_entries {
            let Ok(session_entry) = session_entry else {
                continue;
            };
            let path = session_entry.path();
            if path.extension().and_then(|extension| extension.to_str()) != Some("jsonl") {
                continue;
            }
            if !modified_after(&path, cutoff) {
                continue;
            }
            files.push(path);
        }
    }

    Ok(files)
}

fn collect_cli_probe_files(
    root: &Path,
    cutoff: Option<&std::time::SystemTime>,
) -> Result<Vec<PathBuf>> {
    if !root.exists() {
        return Ok(Vec::new());
    }

    let files = WalkDir::new(root)
        .follow_links(false)
        .into_iter()
        .filter_map(Result::ok)
        .filter(|entry| entry.file_type().is_file())
        .filter(|entry| {
            matches!(
                entry
                    .path()
                    .extension()
                    .and_then(|extension| extension.to_str()),
                Some("jsonl" | "json" | "log")
            )
        })
        .filter(|entry| {
            has_component(entry.path(), "session-state") || has_component(entry.path(), "logs")
        })
        .filter(|entry| modified_after(entry.path(), cutoff))
        .map(|entry| entry.into_path())
        .collect();

    Ok(files)
}

fn has_component(path: &Path, wanted: &str) -> bool {
    path.components().any(|component| {
        component
            .as_os_str()
            .to_string_lossy()
            .eq_ignore_ascii_case(wanted)
    })
}

fn modified_after(path: &Path, cutoff: Option<&std::time::SystemTime>) -> bool {
    match cutoff {
        Some(cutoff) => path
            .metadata()
            .and_then(|metadata| metadata.modified())
            .is_ok_and(|modified| modified >= *cutoff),
        None => true,
    }
}

fn scan_file(path: &Path) -> FileScanResult {
    let mut result = FileScanResult::default();

    let Ok(file) = File::open(path) else {
        result.parse_errors += 1;
        return result;
    };

    let source = if has_component(path, "chatSessions") {
        "vscode.chatSessions"
    } else {
        "copilot.cli.probe"
    };

    let mut reader = BufReader::with_capacity(1024 * 1024, file);
    let mut chat_title = None;
    let mut line_index = 0usize;
    let mut line = Vec::with_capacity(16 * 1024);

    loop {
        line.clear();
        let bytes_read = match reader.read_until(b'\n', &mut line) {
            Ok(bytes_read) => bytes_read,
            Err(_) => {
                result.parse_errors += 1;
                break;
            }
        };
        if bytes_read == 0 {
            break;
        }

        line_index += 1;
        result.scanned_lines += 1;

        if chat_title.is_none() && line_index <= 64 {
            if let Some(title) = quick_extract_title_from_line(&line) {
                chat_title = Some(title);
            } else if contains_bytes(&line, b"customTitle") {
                // Fallback for delta-jsonl shape: {"k":["customTitle"],"v":"…"}
                if let Ok(value) = serde_json::from_slice::<Value>(&line) {
                    if let Some(title) = extract_custom_title(&value) {
                        chat_title = Some(title);
                    }
                }
            }
        }

        if !is_usage_candidate_line(source, &line) {
            continue;
        }

        result.json_candidate_lines += 1;

        match serde_json::from_slice::<Value>(&line) {
            Ok(value) => {
                let mut extraction = LineExtraction::default();
                collect_line_extraction(&value, ContextFields::default(), &mut extraction);
                for raw in extraction.records {
                    let local =
                        enrich_from_response_metadata(raw.context, &extraction.response_metadata);
                    result.records.push(UsageRecord {
                        source: source.to_owned(),
                        hostname: String::new(),
                        timestamp_ms: local.timestamp_ms,
                        local_time_hint: local.timestamp_ms.and_then(format_local_time),
                        chat_title: None,
                        model: raw.model,
                        model_id: local.model_id.as_deref().map(display_model_id),
                        credits: raw.credits,
                        details: raw.details,
                        session_id: local.session_id.clone(),
                        request_id: local.request_id.clone(),
                        response_id: local.response_id.clone(),
                        agent_id: local.agent_id.clone(),
                        file: path.to_string_lossy().into_owned(),
                        line: line_index,
                    });
                }
            }
            Err(_) => {
                result.parse_errors += 1;
                if let Ok(text) = std::str::from_utf8(&line) {
                    collect_records_from_text(source, path, line_index, text, &mut result.records);
                }
            }
        }
    }

    if let Some(title) = chat_title {
        for record in &mut result.records {
            record.chat_title = Some(title.clone());
        }
    }

    result
}

fn contains_bytes(haystack: &[u8], needle: &[u8]) -> bool {
    memmem::find(haystack, needle).is_some()
}

fn is_usage_candidate_line(source: &str, line: &[u8]) -> bool {
    if contains_bytes(line, b"credits") && contains_bytes(line, b"details") {
        return true;
    }

    source == "copilot.cli.probe"
        && contains_bytes(line, b"session.shutdown")
        && contains_bytes(line, b"modelMetrics")
}

fn collect_line_extraction(value: &Value, context: ContextFields, extraction: &mut LineExtraction) {
    match value {
        Value::Array(items) => {
            for item in items {
                collect_line_extraction(item, context.clone(), extraction);
            }
        }
        Value::Object(map) => {
            let mut local = context.clone();
            merge_context_from_object(&mut local, map);
            if let Some(Value::Object(metadata)) = map.get("metadata") {
                merge_context_from_object(&mut local, metadata);
            }

            if let Some(response_id) = local.response_id.clone() {
                let entry = extraction.response_metadata.entry(response_id).or_default();
                merge_context_missing(entry, &local);
            }

            if let Some(details) = map.get("details").and_then(Value::as_str) {
                if let Some((model, credits)) = parse_credit_details(details) {
                    extraction.records.push(RawUsageRecord {
                        context: local.clone(),
                        model,
                        credits,
                        details: details.to_owned(),
                    });
                }
            }

            collect_cli_shutdown_metrics(map, &local, extraction);

            for child in map.values() {
                collect_line_extraction(child, local.clone(), extraction);
            }
        }
        _ => {}
    }
}

fn collect_cli_shutdown_metrics(
    map: &serde_json::Map<String, Value>,
    context: &ContextFields,
    extraction: &mut LineExtraction,
) {
    if map.get("type").and_then(Value::as_str) != Some("session.shutdown") {
        return;
    }

    let Some(model_metrics) = map
        .get("data")
        .and_then(|data| data.get("modelMetrics"))
        .and_then(Value::as_object)
    else {
        return;
    };

    for (model, metrics) in model_metrics {
        let Some(credits) = metrics
            .get("requests")
            .and_then(|requests| requests.get("cost"))
            .and_then(value_as_f64)
        else {
            continue;
        };

        extraction.records.push(RawUsageRecord {
            context: context.clone(),
            model: model.clone(),
            credits,
            details: format!("Copilot CLI {model} • {credits} credits"),
        });
    }
}

fn value_as_f64(value: &Value) -> Option<f64> {
    match value {
        Value::Number(number) => number.as_f64(),
        _ => None,
    }
}

fn merge_context_from_object(context: &mut ContextFields, map: &serde_json::Map<String, Value>) {
    assign_string(&mut context.session_id, map, "sessionId");
    assign_string(&mut context.request_id, map, "requestId");
    assign_string(&mut context.response_id, map, "responseId");
    assign_string(&mut context.model_id, map, "modelId");
    assign_string(&mut context.agent_id, map, "agentId");

    if context.timestamp_ms.is_none() {
        context.timestamp_ms = map.get("timestamp").and_then(|value| {
            value
                .as_i64()
                .or_else(|| value.as_str().and_then(parse_rfc3339_timestamp_ms))
        });
    }

    if let Some(Value::Object(model_state)) = map.get("modelState") {
        if let Some(completed_at) = model_state.get("completedAt").and_then(Value::as_i64) {
            context.timestamp_ms = Some(completed_at);
        }
    }

    if let Some(completed_at) = map.get("completedAt").and_then(Value::as_i64) {
        context.timestamp_ms = Some(completed_at);
    }
}

fn parse_rfc3339_timestamp_ms(timestamp: &str) -> Option<i64> {
    DateTime::parse_from_rfc3339(timestamp)
        .ok()
        .map(|time| time.timestamp_millis())
}

fn assign_string(target: &mut Option<String>, map: &serde_json::Map<String, Value>, key: &str) {
    if target.is_none() {
        if let Some(value) = map.get(key).and_then(Value::as_str) {
            *target = Some(value.to_owned());
        }
    }
}

fn parse_credit_details(details: &str) -> Option<(String, f64)> {
    let trimmed = details.trim();
    let credits_suffix = " credits";
    let before_suffix = trimmed.strip_suffix(credits_suffix)?;
    let mut parts = before_suffix.rsplitn(2, char::is_whitespace);
    let credits_text = parts.next()?.trim();
    let model_part = parts.next()?.trim();

    let credits = credits_text.parse::<f64>().ok()?;
    let model = model_part
        .trim_end_matches(|ch: char| {
            ch.is_whitespace() || !(ch.is_ascii_alphanumeric() || ch == ')' || ch == ']')
        })
        .trim()
        .to_owned();

    if model.is_empty() {
        None
    } else {
        Some((model, credits))
    }
}

fn display_model_id(model_id: &str) -> String {
    model_id
        .strip_prefix("copilot/")
        .unwrap_or(model_id)
        .to_owned()
}

fn format_local_time(timestamp_ms: i64) -> Option<String> {
    let utc = DateTime::<Utc>::from_timestamp_millis(timestamp_ms)?;
    Some(
        utc.with_timezone(&Local)
            .format("%Y-%m-%d %H:%M:%S")
            .to_string(),
    )
}

fn format_local_day(timestamp_ms: i64) -> Option<String> {
    let utc = DateTime::<Utc>::from_timestamp_millis(timestamp_ms)?;
    Some(utc.with_timezone(&Local).format("%Y-%m-%d").to_string())
}

fn collect_records_from_text(
    source: &str,
    path: &Path,
    line_number: usize,
    line: &str,
    records: &mut Vec<UsageRecord>,
) {
    let Some(details_key_index) = line.find("details") else {
        return;
    };
    let Some(credits_index) = line[details_key_index..].find("credits") else {
        return;
    };

    let end = details_key_index + credits_index + "credits".len();
    let start = line[..details_key_index]
        .rfind('"')
        .map(|index| index + 1)
        .unwrap_or(details_key_index);
    let candidate = &line[start..end];

    if let Some((model, credits)) = parse_credit_details(candidate) {
        records.push(UsageRecord {
            source: source.to_owned(),
            hostname: String::new(),
            timestamp_ms: None,
            local_time_hint: None,
            chat_title: None,
            model,
            model_id: None,
            credits,
            details: candidate.to_owned(),
            session_id: None,
            request_id: None,
            response_id: None,
            agent_id: None,
            file: path.to_string_lossy().into_owned(),
            line: line_number,
        });
    }
}

fn write_csv(path: &Path, records: &[UsageRecord], emit_bom: bool) -> Result<()> {
    if path.as_os_str() == "-" {
        let mut writer = csv::Writer::from_writer(std::io::stdout());
        for record in records {
            writer.serialize(record)?;
        }
        writer.flush()?;
        return Ok(());
    }

    let mut file = File::create(path)
        .with_context(|| format!("failed to create CSV output {}", path.display()))?;
    if emit_bom {
        file.write_all(b"\xEF\xBB\xBF")?;
    }

    let mut writer = csv::Writer::from_writer(file);
    for record in records {
        writer.serialize(record)?;
    }
    writer.flush()?;
    Ok(())
}

fn write_json(path: &Path, records: &[UsageRecord], emit_bom: bool) -> Result<()> {
    if path.as_os_str() == "-" {
        println!("{}", serde_json::to_string_pretty(records)?);
        return Ok(());
    }

    let mut file = File::create(path)
        .with_context(|| format!("failed to create JSON output {}", path.display()))?;
    if emit_bom {
        file.write_all(b"\xEF\xBB\xBF")?;
    }
    serde_json::to_writer_pretty(file, records)?;
    Ok(())
}

fn enrich_from_response_metadata(
    mut local: ContextFields,
    response_metadata: &HashMap<String, ContextFields>,
) -> ContextFields {
    if let Some(response_id) = local.response_id.as_ref() {
        if let Some(metadata) = response_metadata.get(response_id) {
            merge_context_missing(&mut local, metadata);
        }
    }
    local
}

fn merge_context_missing(target: &mut ContextFields, source: &ContextFields) {
    if target.session_id.is_none() {
        target.session_id = source.session_id.clone();
    }
    if target.request_id.is_none() {
        target.request_id = source.request_id.clone();
    }
    if target.response_id.is_none() {
        target.response_id = source.response_id.clone();
    }
    if target.model_id.is_none() {
        target.model_id = source.model_id.clone();
    }
    if target.agent_id.is_none() {
        target.agent_id = source.agent_id.clone();
    }
    if target.timestamp_ms.is_none() {
        target.timestamp_ms = source.timestamp_ms;
    }
}

fn extract_custom_title(value: &Value) -> Option<String> {
    let object = value.as_object()?;
    let key = object.get("k")?.as_array()?;
    let is_custom_title = key
        .iter()
        .any(|part| part.as_str().is_some_and(|text| text == "customTitle"));
    if !is_custom_title {
        return None;
    }

    object
        .get("v")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|title| !title.is_empty())
        .map(ToOwned::to_owned)
}

/// Best-effort byte-level scan for the chat title without parsing the entire
/// session document. Handles both shapes we have seen:
///   - delta jsonl header   : {"k":["customTitle"],"v":"…"}
///   - single-object session: {"kind":0,"v":{"customTitle":"…", "title":"…", …}}
fn quick_extract_title_from_line(line: &[u8]) -> Option<String> {
    const NEEDLES: [&[u8]; 2] = [b"\"customTitle\":\"", b"\"title\":\""];
    for needle in NEEDLES {
        let mut search_from = 0;
        while let Some(rel) = memmem::find(&line[search_from..], needle) {
            let start = search_from + rel;
            // Include the opening quote so serde_json can decode the literal.
            let literal_start = start + needle.len() - 1;
            let mut cursor = literal_start + 1;
            while cursor < line.len() {
                let byte = line[cursor];
                if byte == b'\\' {
                    cursor += 2;
                    continue;
                }
                if byte == b'"' {
                    break;
                }
                cursor += 1;
            }
            if cursor >= line.len() {
                break;
            }
            let literal = &line[literal_start..=cursor];
            if let Ok(text) = std::str::from_utf8(literal) {
                if let Ok(decoded) = serde_json::from_str::<String>(text) {
                    let trimmed = decoded.trim();
                    if !trimmed.is_empty() {
                        return Some(trimmed.to_owned());
                    }
                }
            }
            search_from = cursor + 1;
        }
    }
    None
}

fn detect_hostname() -> String {
    if let Some(name) = env::var("COMPUTERNAME")
        .ok()
        .or_else(|| env::var("HOSTNAME").ok())
        .map(|name| sanitize_hostname(&name))
        .filter(|name| !name.is_empty())
    {
        return name;
    }

    #[cfg(unix)]
    {
        for path in ["/proc/sys/kernel/hostname", "/etc/hostname"] {
            if let Ok(text) = fs::read_to_string(path) {
                let cleaned = sanitize_hostname(&text);
                if !cleaned.is_empty() {
                    return cleaned;
                }
            }
        }
    }

    "unknown-host".to_owned()
}

fn sanitize_hostname(raw: &str) -> String {
    raw.trim()
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' || ch == '.' {
                ch
            } else {
                '-'
            }
        })
        .collect::<String>()
        .trim_matches('-')
        .to_owned()
}

fn default_output_path(hostname: &str, format: OutputFormat) -> PathBuf {
    let extension = match format {
        OutputFormat::Csv => "csv",
        OutputFormat::Json => "json",
    };
    PathBuf::from(format!("copilot-usage-{hostname}.{extension}"))
}

fn default_html_path(output_path: &Path, hostname: &str) -> PathBuf {
    // Place the HTML next to the primary output file, replacing the extension.
    let mut candidate = output_path.to_path_buf();
    if candidate.set_extension("html") {
        return candidate;
    }
    PathBuf::from(format!("copilot-usage-{hostname}.html"))
}

const REPORT_TEMPLATE: &str = include_str!("report-template.html");
const REPORT_DATA_PLACEHOLDER: &str = "__GH_USAGE_DATA__";

fn write_html(path: &Path, records: &[UsageRecord], primary_host: &str) -> Result<()> {
    let payload = serde_json::json!({
        "generatedAt": Local::now().format("%Y-%m-%d %H:%M:%S").to_string(),
        "primaryHost": primary_host,
        "records": records,
    });

    let mut data = serde_json::to_string(&payload)?;
    // Avoid prematurely closing the inline <script> block. JSON has no literal "</",
    // so any "</" inside string values is escaped to "<\/" which is still valid JSON.
    data = data.replace("</", "<\\/");

    let html = REPORT_TEMPLATE.replace(REPORT_DATA_PLACEHOLDER, &data);

    let mut file = File::create(path)
        .with_context(|| format!("failed to create HTML output {}", path.display()))?;
    file.write_all(html.as_bytes())?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{
        collect_line_extraction, extract_custom_title, parse_credit_details,
        quick_extract_title_from_line, ContextFields, LineExtraction,
    };
    use serde_json::json;

    #[test]
    fn parses_credit_details_with_bullet_separator() {
        let (model, credits) = parse_credit_details("GPT-5.5 • 105.7 credits").unwrap();

        assert_eq!(model, "GPT-5.5");
        assert_eq!(credits, 105.7);
    }

    #[test]
    fn extracts_custom_title_from_chat_session_line() {
        let value = json!({"kind":1,"k":["customTitle"],"v":"Switching speed optimization notes"});

        assert_eq!(
            extract_custom_title(&value).as_deref(),
            Some("Switching speed optimization notes")
        );
    }

    #[test]
    fn quick_extracts_nested_custom_title() {
        let line = br#"{"kind":0,"v":{"version":3,"customTitle":"\u65b0\u5efaAIFriend\u76ee\u5f55\u548c\u63d2\u4ef6","title":"fallback"}}"#;
        assert_eq!(
            quick_extract_title_from_line(line).as_deref(),
            Some("\u{65b0}\u{5efa}AIFriend\u{76ee}\u{5f55}\u{548c}\u{63d2}\u{4ef6}")
        );
    }

    #[test]
    fn quick_extracts_falls_back_to_title() {
        let line = br#"{"kind":0,"v":{"title":"plain title"}}"#;
        assert_eq!(
            quick_extract_title_from_line(line).as_deref(),
            Some("plain title")
        );
    }

    #[test]
    fn quick_extracts_handles_escaped_quote() {
        let line = br#"{"customTitle":"He said \"hi\" yo"}"#;
        assert_eq!(
            quick_extract_title_from_line(line).as_deref(),
            Some("He said \"hi\" yo")
        );
    }

    #[test]
    fn extracts_copilot_cli_shutdown_model_metrics() {
        let value = json!({
            "type": "session.shutdown",
            "timestamp": "2026-05-18T10:56:39.403Z",
            "data": {
                "modelMetrics": {
                    "gpt-5.4": {
                        "requests": {"count": 1, "cost": 1},
                        "usage": {"inputTokens": 20028, "outputTokens": 62}
                    }
                }
            }
        });

        let mut extraction = LineExtraction::default();
        collect_line_extraction(&value, ContextFields::default(), &mut extraction);

        assert_eq!(extraction.records.len(), 1);
        assert_eq!(extraction.records[0].model, "gpt-5.4");
        assert_eq!(extraction.records[0].credits, 1.0);
        assert_eq!(
            extraction.records[0].context.timestamp_ms,
            Some(1779101799403)
        );
    }
}
