use std::collections::{BTreeMap, HashMap, HashSet};
use std::env;
use std::fs::{self, File};
use std::io::{BufRead, BufReader, IsTerminal, Write};
use std::path::{Path, PathBuf};
use std::time::Instant;

use anyhow::{Context, Result};
use chrono::{DateTime, Local, Utc};
use clap::{Parser, ValueEnum};
use memchr::memmem;
use rayon::prelude::*;
use rusqlite::{Connection, OpenFlags};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use walkdir::WalkDir;

mod vscode;

#[cfg(test)]
mod view_tests;

#[derive(Debug, Parser)]
#[command(name = "gh-usage")]
#[command(
    about = "Scan local GitHub Copilot / VS Code Chat usage records and export credit usage as CSV",
    version
)]
struct Cli {
    /// VS Code workspaceStorage root. Defaults to the standard VS Code user-data path for the current OS.
    #[arg(long)]
    vscode_workspace_storage: Option<PathBuf>,

    /// Copilot CLI root. Defaults to ~/.copilot.
    #[arg(long)]
    copilot_cli_root: Option<PathBuf>,

    /// Include Copilot CLI records (kept for compatibility; CLI scanning is now enabled by default).
    #[arg(long, hide = true)]
    include_cli_logs: bool,

    /// Skip Copilot CLI records and only scan VS Code chat sessions.
    #[arg(long)]
    no_cli_logs: bool,

    /// Only scan files modified within N days.
    #[arg(long)]
    since_days: Option<u64>,

    /// Maximum files to scan, useful while experimenting.
    #[arg(long)]
    max_files: Option<usize>,

    /// Output CSV path. Use '-' for stdout. Defaults to copilot-usage-<hostname>.csv beside the binary's working directory.
    #[arg(long, short)]
    output: Option<PathBuf>,

    /// Output format. CSV is the default for spreadsheet inspection.
    #[arg(long, value_enum, default_value_t = OutputFormat::Csv)]
    format: OutputFormat,

    /// Override the machine hostname embedded into records. Defaults to the detected OS hostname.
    #[arg(long)]
    hostname: Option<String>,

    /// Explicit path for the HTML summary report. Implies HTML output. Defaults to copilot-usage-<hostname>.html beside the CSV.
    #[arg(long)]
    html: Option<PathBuf>,

    /// Skip writing the HTML summary report. HTML is generated by default whenever a file output is produced.
    #[arg(long)]
    no_html: bool,

    /// Generate HTML and open it with the default browser, without a keypress pause.
    /// Also accepts `gh-usage -view` (as the first argument).
    #[arg(long, short = 'v', conflicts_with = "no_html")]
    view: bool,

    /// Print a short summary to stderr after writing output.
    #[arg(long)]
    summary: bool,

    /// Do not write a UTF-8 BOM for file output. By default files include BOM for Windows Excel compatibility.
    #[arg(long)]
    no_bom: bool,

    /// Merge mode. Read every `copilot-usage-*.csv` in DIR (or the current directory when DIR is omitted)
    /// and render a combined `copilot-usage-merged.html` next to those CSVs. Skips the local VS Code scan.
    #[arg(long, value_name = "DIR", num_args = 0..=1, default_missing_value = ".")]
    merge: Option<PathBuf>,
}

#[derive(Debug, Clone, Copy, ValueEnum)]
enum OutputFormat {
    Csv,
    Json,
}

#[derive(Debug, Clone, Default)]
struct ContextFields {
    session_id: Option<String>,
    request_id: Option<String>,
    response_id: Option<String>,
    model_id: Option<String>,
    agent_id: Option<String>,
    timestamp_ms: Option<i64>,
    total_elapsed_ms: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct UsageRecord {
    #[serde(default)]
    source: String,
    #[serde(default)]
    hostname: String,
    #[serde(default)]
    timestamp_ms: Option<i64>,
    #[serde(default)]
    local_time_hint: Option<String>,
    #[serde(default)]
    chat_title: Option<String>,
    #[serde(default)]
    model: String,
    #[serde(default)]
    model_id: Option<String>,
    #[serde(default)]
    credits: f64,
    #[serde(default)]
    details: String,
    #[serde(default)]
    session_id: Option<String>,
    #[serde(default)]
    request_id: Option<String>,
    #[serde(default)]
    response_id: Option<String>,
    #[serde(default)]
    agent_id: Option<String>,
    /// Workspace folder name this session belongs to (derived from workspace.json).
    #[serde(default)]
    project: Option<String>,
    /// Wall-clock duration of this single exchange in milliseconds (timings.totalElapsed).
    #[serde(default)]
    duration_ms: Option<i64>,
    /// 1-based position of this exchange within its parent session.
    #[serde(default)]
    turn_index: Option<u32>,
    /// Total number of exchanges recorded for the parent session.
    #[serde(default)]
    session_total: Option<u32>,
    #[serde(default)]
    file: String,
    #[serde(default)]
    line: usize,
}

#[derive(Debug, Default)]
struct ScanStats {
    scanned_files: usize,
    scanned_lines: usize,
    json_candidate_lines: usize,
    parse_errors: usize,
}

#[derive(Debug, Default)]
struct FileScanResult {
    records: Vec<UsageRecord>,
    scanned_lines: usize,
    json_candidate_lines: usize,
    parse_errors: usize,
}

#[derive(Debug, Default)]
struct LineExtraction {
    response_metadata: HashMap<String, ContextFields>,
    records: Vec<RawUsageRecord>,
}

#[derive(Debug)]
struct RawUsageRecord {
    context: ContextFields,
    model: String,
    credits: f64,
    details: String,
}

#[derive(Debug)]
struct CliUsageAggregate {
    source_path: PathBuf,
    source_line: usize,
    session_id: String,
    turn_index: Option<u32>,
    model: String,
    credits: f64,
    request_count: usize,
    started_at_ms: i64,
    completed_at_ms: i64,
    title: Option<String>,
    project: Option<String>,
}

#[derive(Debug)]
struct CliEventMessage {
    line: usize,
    timestamp_ms: i64,
    model: String,
    is_subagent: bool,
    api_call_id: String,
}

#[derive(Debug)]
struct CliShutdownMetric {
    line: usize,
    timestamp_ms: i64,
    model: String,
    credits: f64,
}

#[derive(Debug, Default)]
struct CliSessionEvents {
    path: PathBuf,
    scanned_lines: usize,
    title: Option<String>,
    project: Option<String>,
    messages: Vec<CliEventMessage>,
    used_api_calls: HashSet<String>,
    shutdown_metrics: Vec<CliShutdownMetric>,
}

#[derive(Debug, Default)]
struct CliWorkspaceMetadata {
    title: Option<String>,
    project: Option<String>,
}

// Only normalize the leading convenience spelling. Never rewrite option values
// (e.g. --hostname -view) or anything following the `--` separator.
fn normalize_view_args(
    args: impl IntoIterator<Item = impl Into<std::ffi::OsString>>,
) -> Vec<std::ffi::OsString> {
    let mut args: Vec<_> = args.into_iter().map(Into::into).collect();
    if let Some(arg) = args.get_mut(1)
        && arg == "-view"
    {
        *arg = "--view".into();
    }
    args
}

fn resolve_html_path(cli: &Cli, output: &Path, hostname: &str) -> Option<PathBuf> {
    if cli.no_html {
        None
    } else if let Some(path) = &cli.html {
        Some(path.clone())
    } else if output.as_os_str() == "-" {
        cli.view.then(|| PathBuf::from(format!("copilot-usage-{hostname}.html")))
    } else {
        Some(default_html_path(output, hostname))
    }
}

fn main() -> Result<()> {
    let total_started = Instant::now();
    let no_args = env::args_os().len() == 1;
    // Treat this as a true double-click only when launched directly from
    // Explorer (parent process is explorer.exe). Terminal runs, CI, and the
    // winget package-validation sandbox all have a different parent process, so
    // they skip the keypress pause entirely and exit cleanly after writing the
    // report files. This is what keeps automated installation verification from
    // hanging on `wait_for_any_key()`.
    let double_clicked = no_args && launched_from_explorer();
    let cli = Cli::parse_from(normalize_view_args(env::args_os()));

    if let Some(dir) = cli.merge.clone() {
        return run_merge(&dir, double_clicked, cli.view, cli.html.as_deref());
    }

    let hostname = cli
        .hostname
        .clone()
        .map(|name| sanitize_hostname(&name))
        .unwrap_or_else(detect_hostname);

    let output_path = cli
        .output
        .clone()
        .unwrap_or_else(|| default_output_path(&hostname, cli.format));

    let html_path = resolve_html_path(&cli, &output_path, &hostname);

    let vscode_root = cli
        .vscode_workspace_storage
        .or_else(default_vscode_workspace_storage)
        .context(
            "Could not determine VS Code workspaceStorage path; pass --vscode-workspace-storage",
        )?;

    let copilot_cli_root = cli.copilot_cli_root.or_else(default_copilot_cli_root);
    let cutoff = cli.since_days.map(cutoff_system_time);

    let mut files = collect_vscode_chat_session_files(&vscode_root, cutoff.as_ref())?;
    let mut cli_database_result = None;

    if (!cli.no_cli_logs || cli.include_cli_logs)
        && let Some(root) = copilot_cli_root.as_ref()
    {
        match scan_cli_usage_database(root, cutoff.as_ref()) {
            Ok(Some(result)) => cli_database_result = Some(result),
            Ok(None) => files.extend(collect_cli_probe_files(root, cutoff.as_ref())?),
            Err(error) => {
                eprintln!(
                    "warning: could not read Copilot CLI session store ({error:#}); falling back to logs"
                );
                files.extend(collect_cli_probe_files(root, cutoff.as_ref())?);
            }
        }
    }

    files.sort();
    files.dedup();

    if let Some(max_files) = cli.max_files {
        files.truncate(max_files);
    }
    let scanned_files = files.len() + usize::from(cli_database_result.is_some());
    let project_map = build_project_map(&files);
    let mut file_results: Vec<FileScanResult> = files
        .par_iter()
        .map(|path| scan_file(path, &project_map))
        .collect();
    if let Some(result) = cli_database_result {
        file_results.push(result);
    }
    let mut stats = ScanStats {
        scanned_files,
        ..ScanStats::default()
    };
    let mut records = Vec::new();

    for result in file_results {
        stats.scanned_lines += result.scanned_lines;
        stats.json_candidate_lines += result.json_candidate_lines;
        stats.parse_errors += result.parse_errors;
        records.extend(result.records);
    }

    records.sort_by(|a, b| {
        a.timestamp_ms
            .cmp(&b.timestamp_ms)
            .then_with(|| a.file.cmp(&b.file))
            .then_with(|| a.line.cmp(&b.line))
            .then_with(|| a.response_id.cmp(&b.response_id))
    });
    records.dedup_by(|a, b| {
        a.file == b.file
            && a.line == b.line
            && a.request_id == b.request_id
            && a.turn_index == b.turn_index
            && a.response_id == b.response_id
            && a.details == b.details
    });
    for record in &mut records {
        record.hostname = hostname.clone();
    }
    assign_turn_indices(&mut records);

    match cli.format {
        OutputFormat::Csv => write_csv(&output_path, &records, !cli.no_bom)?,
        OutputFormat::Json => write_json(&output_path, &records, !cli.no_bom)?,
    }
    if let Some(html_path) = html_path.as_ref() {
        write_html(html_path, &records, &hostname)?;
    }
    let total_ms = total_started.elapsed().as_millis();

    if no_args || cli.summary {
        let report = build_summary_report(
            &output_path,
            html_path.as_deref(),
            &records,
            &stats,
            total_ms,
        );
        if output_path.as_os_str() == "-" {
            eprint!("{report}");
        } else {
            print!("{report}");
        }
    }

    if cli.view {
        open_path(html_path.as_deref().context("--view requires HTML output")?)?;
    } else if double_clicked && console_is_interactive() {
        show_double_click_exit_notice(&output_path, html_path.as_deref());
    }

    Ok(())
}

/// Returns true only when the program is attached to a real interactive
/// console. In non-interactive environments (CI, piped/redirected I/O, the
/// winget installation-verification sandbox) stdin is not a terminal, so we
/// must not pause for a keypress or implicitly open the browser. An explicit
/// --view request is handled separately and never waits for a keypress.
fn console_is_interactive() -> bool {
    std::io::stdin().is_terminal() && std::io::stdout().is_terminal()
}

fn show_double_click_exit_notice(output: &Path, html: Option<&Path>) {
    println!();
    println!(
        "CSV saved to {}",
        output.display()
    );
    println!(
        "  Every parsed Copilot usage record is in there - import it into Excel,"
    );
    println!(
        "  Power BI, or pipe it through your own scripts for deeper analysis."
    );
    if let Some(html) = html {
        println!();
        println!("HTML report saved to {}", html.display());
        println!(
            "  A self-contained, offline-friendly page with charts, host/model"
        );
        println!(
            "  filters, and a paginated record table. Safe to email or archive."
        );
        // Open the report automatically so viewing it never requires a keypress.
        // This branch only runs on a genuine Explorer double-click; terminal,
        // CI, and the winget validation sandbox never reach here.
        if let Err(error) = open_path(html) {
            eprintln!("warning: {error:#}");
        }
        println!();
        println!(">> The report is ready to view.");
        println!("   If it didn't open, double-click the HTML file above, or run");
        println!("   `gh-usage --html <PATH>` to regenerate it at a path you choose.");
    } else {
        println!();
        println!("HTML report skipped (--no-html). The CSV above is your full dataset.");
        println!("   Re-run without --no-html (or `gh-usage --html <PATH>`) to build it.");
    }
    println!();
    println!(">> Press any key to close this window. Your files are already saved.");
    wait_for_any_key();
}

fn open_path(path: &Path) -> Result<()> {
    // Absolute paths avoid interpreting filenames as launcher options. Do not
    // canonicalize: Windows extended-length paths can confuse shell handlers.
    let absolute = std::path::absolute(path)?;
    anyhow::ensure!(absolute.is_file(), "HTML report not found: {}", absolute.display());
    open::that(&absolute).with_context(|| {
        format!("HTML saved to {}, but could not launch its default browser", absolute.display())
    })?;
    // Keep stdout clean for --output - and report only the launch request,
    // not a browser-rendering success that we cannot observe here.
    eprintln!("Requested browser opening: {}", absolute.display());
    Ok(())
}

// Detects whether the process was launched by double-clicking the executable
// in Windows Explorer (parent process is explorer.exe). We use this to gate the
// keypress pause so only genuine double-clicks wait for a key; terminal, CI, and
// the winget validation sandbox have a different parent and exit immediately.
#[cfg(windows)]
fn launched_from_explorer() -> bool {
    windows_parent_process_name()
        .as_deref()
        .is_some_and(|name| name.eq_ignore_ascii_case("explorer.exe"))
}

#[cfg(not(windows))]
fn launched_from_explorer() -> bool {
    false
}

#[cfg(windows)]
fn wait_for_any_key() {
    use windows_sys::Win32::Foundation::INVALID_HANDLE_VALUE;
    use windows_sys::Win32::System::Console::{
        GetConsoleMode, GetStdHandle, ReadConsoleW, SetConsoleMode, ENABLE_ECHO_INPUT,
        ENABLE_LINE_INPUT, STD_INPUT_HANDLE,
    };

    unsafe {
        let handle = GetStdHandle(STD_INPUT_HANDLE);
        if handle == INVALID_HANDLE_VALUE {
            return;
        }

        let mut original_mode = 0;
        if GetConsoleMode(handle, &mut original_mode) == 0 {
            let mut input = String::new();
            let _ = std::io::stdin().read_line(&mut input);
            return;
        }

        let single_key_mode = original_mode & !(ENABLE_LINE_INPUT | ENABLE_ECHO_INPUT);
        let _ = SetConsoleMode(handle, single_key_mode);

        let mut buffer = [0u16; 1];
        let mut chars_read = 0;
        let _ = ReadConsoleW(
            handle,
            buffer.as_mut_ptr().cast(),
            buffer.len() as u32,
            &mut chars_read,
            std::ptr::null_mut(),
        );

        let _ = SetConsoleMode(handle, original_mode);
    }
}

#[cfg(not(windows))]
fn wait_for_any_key() {}

#[cfg(windows)]
fn windows_parent_process_name() -> Option<String> {
    use windows_sys::Win32::Foundation::{CloseHandle, INVALID_HANDLE_VALUE};
    use windows_sys::Win32::System::Diagnostics::ToolHelp::{
        CreateToolhelp32Snapshot, Process32FirstW, Process32NextW, PROCESSENTRY32W,
        TH32CS_SNAPPROCESS,
    };

    unsafe {
        let snapshot = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
        if snapshot == INVALID_HANDLE_VALUE {
            return None;
        }

        let mut entry = std::mem::zeroed::<PROCESSENTRY32W>();
        entry.dwSize = std::mem::size_of::<PROCESSENTRY32W>() as u32;

        let current_pid = std::process::id();
        let mut parent_pid = None;

        if Process32FirstW(snapshot, &mut entry) != 0 {
            loop {
                if entry.th32ProcessID == current_pid {
                    parent_pid = Some(entry.th32ParentProcessID);
                    break;
                }

                if Process32NextW(snapshot, &mut entry) == 0 {
                    break;
                }
            }
        }

        let Some(parent_pid) = parent_pid else {
            let _ = CloseHandle(snapshot);
            return None;
        };

        if Process32FirstW(snapshot, &mut entry) != 0 {
            loop {
                if entry.th32ProcessID == parent_pid {
                    let name = wide_process_name_to_string(&entry.szExeFile);
                    let _ = CloseHandle(snapshot);
                    return name;
                }

                if Process32NextW(snapshot, &mut entry) == 0 {
                    break;
                }
            }
        }

        let _ = CloseHandle(snapshot);
        None
    }
}

#[cfg(windows)]
#[allow(dead_code)]
fn wide_process_name_to_string(buffer: &[u16]) -> Option<String> {
    let len = buffer.iter().position(|ch| *ch == 0).unwrap_or(buffer.len());
    if len == 0 {
        None
    } else {
        Some(String::from_utf16_lossy(&buffer[..len]))
    }
}

/// Merge mode: read every `copilot-usage-*.csv` in `dir`, combine + dedupe,
/// render a single `copilot-usage-merged.html` next to those CSVs.
fn run_merge(dir: &Path, double_clicked: bool, view: bool, html: Option<&Path>) -> Result<()> {
    if !dir.is_dir() {
        anyhow::bail!(
            "merge target is not a directory: {}",
            dir.display()
        );
    }

    let mut csv_files: Vec<PathBuf> = Vec::new();
    for entry in fs::read_dir(dir)
        .with_context(|| format!("read_dir failed for {}", dir.display()))?
    {
        let entry = entry?;
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        let name = match path.file_name().and_then(|s| s.to_str()) {
            Some(n) => n,
            None => continue,
        };
        let lower = name.to_ascii_lowercase();
        if !lower.starts_with("copilot-usage-") || !lower.ends_with(".csv") {
            continue;
        }
        // Skip our own merged outputs so re-running is idempotent.
        if lower == "copilot-usage-merged.csv" {
            continue;
        }
        csv_files.push(path);
    }
    csv_files.sort();

    if csv_files.is_empty() {
        anyhow::bail!(
            "no copilot-usage-*.csv files found in {}",
            dir.display()
        );
    }

    let mut records: Vec<UsageRecord> = Vec::new();
    let mut per_file: Vec<(PathBuf, usize)> = Vec::new();
    let mut row_errors: usize = 0;
    for path in &csv_files {
        let before = records.len();
        let mut reader = csv::ReaderBuilder::new()
            .flexible(true)
            .from_path(path)
            .with_context(|| format!("open csv {}", path.display()))?;
        for row in reader.deserialize::<UsageRecord>() {
            match row {
                Ok(record) => records.push(record),
                Err(_) => row_errors += 1,
            }
        }
        per_file.push((path.clone(), records.len() - before));
    }

    // Backfill hostname for legacy CSVs (pre-hostname column) using the file stem.
    for (path, _) in &per_file {
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_default();
        if let Some(host_from_name) = stem.strip_prefix("copilot-usage-") {
            for record in records.iter_mut().filter(|r| r.hostname.is_empty()) {
                record.hostname = host_from_name.to_owned();
            }
        }
    }

    records.sort_by(|a, b| {
        a.hostname
            .cmp(&b.hostname)
            .then_with(|| a.timestamp_ms.cmp(&b.timestamp_ms))
            .then_with(|| a.file.cmp(&b.file))
            .then_with(|| a.line.cmp(&b.line))
            .then_with(|| a.response_id.cmp(&b.response_id))
    });
    records.dedup_by(|a, b| {
        a.hostname == b.hostname
            && a.file == b.file
            && a.line == b.line
            && a.request_id == b.request_id
            && a.turn_index == b.turn_index
            && a.response_id == b.response_id
            && a.details == b.details
    });
    assign_turn_indices(&mut records);

    let hosts: std::collections::BTreeSet<String> =
        records.iter().map(|r| r.hostname.clone()).collect();
    let primary_host = hosts
        .iter()
        .next()
        .cloned()
        .unwrap_or_else(|| "merged".to_owned());

    let html_path = html.map(Path::to_path_buf)
        .unwrap_or_else(|| dir.join("copilot-usage-merged.html"));
    write_html(&html_path, &records, &primary_host)?;

    // Compact merge summary, mirroring the look of the regular scan report.
    const INNER: usize = 54;
    let row = |content: String| -> String {
        let len = content.chars().count();
        let padded = if len < INNER {
            format!("{content}{}", " ".repeat(INNER - len))
        } else {
            content.chars().take(INNER).collect()
        };
        format!("| {padded} |\n")
    };
    let header = |title: &str| -> String {
        let prefix = format!("- {title} ");
        let pad = (INNER + 2).saturating_sub(prefix.chars().count());
        format!("+{prefix}{}+\n", "-".repeat(pad))
    };
    let plain_border = || -> String { format!("+{}+\n", "-".repeat(INNER + 2)) };

    let total_credits = normalize_zero(records.iter().map(|r| r.credits).sum());
    let host_list: Vec<&str> = hosts.iter().map(String::as_str).collect();

    let mut out = String::new();
    out.push_str(&header("GitHub Copilot Usage - Merge"));
    out.push_str(&row(format!(
        "{:<14}{:>12}  {:<14}{:>12}",
        "csv files",
        csv_files.len(),
        "row errors",
        row_errors
    )));
    out.push_str(&row(format!(
        "{:<14}{:>12}  {:<14}{:>12}",
        "records",
        records.len(),
        "hosts",
        hosts.len()
    )));
    out.push_str(&row(format!(
        "{:<14}{:>12}  {:<14}{:>12}",
        "total credits",
        format!("{:.1}", total_credits),
        "target dir",
        clip(&dir.display().to_string(), 12)
    )));

    out.push_str(&header("Sources"));
    for (path, count) in &per_file {
        let file_name = path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or("<unknown>");
        out.push_str(&row(format!(
            "{:<40}{:>14}",
            clip(file_name, 40),
            format!("{count} rows")
        )));
    }

    out.push_str(&header("Hosts"));
    out.push_str(&row(clip(&host_list.join(", "), INNER)));

    out.push_str(&header("Output"));
    out.push_str(&row(format!(
        "html  {}",
        clip(&html_path.display().to_string(), INNER - 6)
    )));
    out.push_str(&plain_border());
    print!("{out}");

    if view {
        open_path(&html_path)?;
    } else if double_clicked && console_is_interactive() {
        show_merge_exit_notice(&html_path, &host_list);
    }
    Ok(())
}

fn show_merge_exit_notice(html: &Path, hosts: &[&str]) {
    println!();
    println!("Merged HTML report saved to {}", html.display());
    println!(
        "  Combined data from {} machine(s): {}",
        hosts.len(),
        hosts.join(", ")
    );
    println!(
        "  Open it in any browser - charts, filters, and pagination work offline,"
    );
    println!(
        "  and the single file is safe to email or archive."
    );
    // Open automatically; only reached on a real Explorer double-click.
    if let Err(error) = open_path(html) {
        eprintln!("warning: {error:#}");
    }
    println!();
    println!(">> The merged report is ready to view.");
    println!("   If it didn't open, double-click the HTML file above.");
    println!();
    println!(">> Press any key to close this window. The HTML is already saved.");
    wait_for_any_key();
}

fn build_summary_report(
    output: &Path,
    html: Option<&Path>,
    records: &[UsageRecord],
    stats: &ScanStats,
    total_ms: u128,
) -> String {
    let total_credits = normalize_zero(records.iter().map(|record| record.credits).sum());
    let mut daily: BTreeMap<String, (usize, f64)> = BTreeMap::new();

    for record in records {
        let day = record
            .timestamp_ms
            .and_then(format_local_day)
            .unwrap_or_else(|| "unknown-date".to_owned());
        let entry = daily.entry(day).or_default();
        entry.0 += 1;
        entry.1 += record.credits;
    }

    let active_days = daily
        .keys()
        .filter(|day| day.as_str() != "unknown-date")
        .count();
    let average_per_active_day = if active_days > 0 {
        normalize_zero(total_credits / active_days as f64)
    } else {
        0.0
    };

    // Layout: outer width 58, inner content width 54.
    const INNER: usize = 54;
    let row = |content: String| -> String {
        let len = content.chars().count();
        let padded = if len < INNER {
            format!("{content}{}", " ".repeat(INNER - len))
        } else {
            content.chars().take(INNER).collect()
        };
        format!("| {padded} |\n")
    };
    let header = |title: &str| -> String {
        // Inner dashed span between the two `+` corners must equal INNER + 2.
        let prefix = format!("- {title} ");
        let pad = (INNER + 2).saturating_sub(prefix.chars().count());
        format!("+{prefix}{}+\n", "-".repeat(pad))
    };
    let plain_border = || -> String { format!("+{}+\n", "-".repeat(INNER + 2)) };

    let kv2 = |lk: &str, lv: String, rk: &str, rv: String| -> String {
        // 14 label + 12 value + 2 sep + 14 label + 12 value = 54
        row(format!(
            "{:<14}{:>12}  {:<14}{:>12}",
            lk, lv, rk, rv
        ))
    };

    let mut report = String::new();
    report.push_str(&header("GitHub Copilot Usage"));
    report.push_str(&kv2(
        "records",
        records.len().to_string(),
        "scanned files",
        stats.scanned_files.to_string(),
    ));
    report.push_str(&kv2(
        "total credits",
        format!("{:.1}", total_credits),
        "candidate lines",
        stats.json_candidate_lines.to_string(),
    ));
    report.push_str(&kv2(
        "active days",
        active_days.to_string(),
        "parse errors",
        stats.parse_errors.to_string(),
    ));
    report.push_str(&kv2(
        "avg / day",
        format!("{:.1}", average_per_active_day),
        "total time",
        format!("{:.2} s", total_ms as f64 / 1000.0),
    ));

    if !daily.is_empty() {
        report.push_str(&header("Daily credits"));
        for (day, (count, credits)) in &daily {
            // 12 date + 6 records right + 11 " records   " + 12 credits right + 13 " credits   " = 54
            report.push_str(&row(format!(
                "{:<12}{:>5} records   {:>10.2} credits     ",
                day, count, credits
            )));
        }
    }

    report.push_str(&header("Files"));
    report.push_str(&row(format!("csv   {}", clip(&output.display().to_string(), INNER - 6))));
    if let Some(html) = html {
        report.push_str(&row(format!("html  {}", clip(&html.display().to_string(), INNER - 6))));
    } else {
        report.push_str(&row("html  (disabled via --no-html)".to_owned()));
    }
    report.push_str(&plain_border());
    report
}

fn clip(s: &str, max: usize) -> String {
    let count = s.chars().count();
    if count <= max {
        return s.to_owned();
    }
    // Keep tail (filename) visible; replace head with "…".
    let skip = count - (max - 1);
    let mut out = String::from("…");
    out.extend(s.chars().skip(skip));
    out
}

fn default_vscode_workspace_storage() -> Option<PathBuf> {
    let candidates = vscode_workspace_storage_candidates();

    candidates
        .iter()
        .find(|path| path.exists())
        .cloned()
        .or_else(|| candidates.into_iter().next())
}

fn vscode_workspace_storage_candidates() -> Vec<PathBuf> {
    vscode_user_data_dirs()
        .into_iter()
        .map(|path| path.join("User").join("workspaceStorage"))
        .collect()
}

#[cfg(windows)]
fn vscode_user_data_dirs() -> Vec<PathBuf> {
    env::var_os("APPDATA")
        .map(PathBuf::from)
        .map(|path| vec![path.join("Code"), path.join("Code - Insiders")])
        .unwrap_or_default()
}

#[cfg(target_os = "macos")]
fn vscode_user_data_dirs() -> Vec<PathBuf> {
    home_dir()
        .map(|home| {
            let application_support = home.join("Library").join("Application Support");
            vec![
                application_support.join("Code"),
                application_support.join("Code - Insiders"),
            ]
        })
        .unwrap_or_default()
}

#[cfg(all(unix, not(target_os = "macos")))]
fn vscode_user_data_dirs() -> Vec<PathBuf> {
    let config_home = env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .or_else(|| home_dir().map(|home| home.join(".config")));

    config_home
        .map(|path| vec![path.join("Code"), path.join("Code - Insiders")])
        .unwrap_or_default()
}

fn normalize_zero(value: f64) -> f64 {
    if value.abs() < f64::EPSILON {
        0.0
    } else {
        value
    }
}

fn default_copilot_cli_root() -> Option<PathBuf> {
    home_dir().map(|path| path.join(".copilot"))
}

fn home_dir() -> Option<PathBuf> {
    env::var_os("HOME")
        .or_else(|| env::var_os("USERPROFILE"))
        .map(PathBuf::from)
}

fn cutoff_system_time(days: u64) -> std::time::SystemTime {
    std::time::SystemTime::now() - std::time::Duration::from_secs(days.saturating_mul(24 * 60 * 60))
}

fn collect_vscode_chat_session_files(
    root: &Path,
    cutoff: Option<&std::time::SystemTime>,
) -> Result<Vec<PathBuf>> {
    if !root.exists() {
        return Ok(Vec::new());
    }

    let mut files = Vec::new();
    for workspace_entry in fs::read_dir(root)? {
        let Ok(workspace_entry) = workspace_entry else {
            continue;
        };
        let Ok(file_type) = workspace_entry.file_type() else {
            continue;
        };
        if !file_type.is_dir() {
            continue;
        }

        let chat_sessions = workspace_entry.path().join("chatSessions");
        let Ok(session_entries) = fs::read_dir(chat_sessions) else {
            continue;
        };

        for session_entry in session_entries {
            let Ok(session_entry) = session_entry else {
                continue;
            };
            let path = session_entry.path();
            if path.extension().and_then(|extension| extension.to_str()) != Some("jsonl") {
                continue;
            }
            if !modified_after(&path, cutoff) {
                continue;
            }
            files.push(path);
        }
    }

    Ok(files)
}

fn collect_cli_probe_files(
    root: &Path,
    cutoff: Option<&std::time::SystemTime>,
) -> Result<Vec<PathBuf>> {
    if !root.exists() {
        return Ok(Vec::new());
    }

    let files = WalkDir::new(root)
        .follow_links(false)
        .into_iter()
        .filter_map(Result::ok)
        .filter(|entry| entry.file_type().is_file())
        .filter(|entry| {
            matches!(
                entry
                    .path()
                    .extension()
                    .and_then(|extension| extension.to_str()),
                Some("jsonl" | "json" | "log")
            )
        })
        .filter(|entry| {
            has_component(entry.path(), "session-state") || has_component(entry.path(), "logs")
        })
        .filter(|entry| modified_after(entry.path(), cutoff))
        .map(|entry| entry.into_path())
        .collect();

    Ok(files)
}

/// Correlates Copilot CLI `events.jsonl` traces with the precise usage ledger.
/// Newer CLI builds persist every model call in `assistant_usage_events`,
/// including calls from an active session, while JSONL remains the report's
/// traceable source path. Returning `None` means this is an older store and the
/// caller should use the generic JSONL/log probe instead.
fn scan_cli_usage_database(
    root: &Path,
    cutoff: Option<&std::time::SystemTime>,
) -> Result<Option<FileScanResult>> {
    let path = root.join("session-store.db");
    if !path.is_file() {
        return Ok(None);
    }

    let connection = Connection::open_with_flags(
        &path,
        OpenFlags::SQLITE_OPEN_READ_ONLY | OpenFlags::SQLITE_OPEN_NO_MUTEX,
    )
    .with_context(|| format!("open Copilot CLI database {}", path.display()))?;

    let has_usage_table: bool = connection
        .query_row(
            "SELECT EXISTS(SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'assistant_usage_events')",
            [],
            |row| row.get(0),
        )
        .with_context(|| format!("inspect Copilot CLI database {}", path.display()))?;
    if !has_usage_table {
        return Ok(None);
    }

    let cutoff_ms = cutoff.and_then(system_time_to_unix_ms);
    scan_cli_usage_connection(&connection, &path, cutoff_ms).map(Some)
}

fn scan_cli_usage_connection(
    connection: &Connection,
    source_path: &Path,
    cutoff_ms: Option<i64>,
) -> Result<FileScanResult> {
    const NANO_AIU_PER_CREDIT: f64 = 1_000_000_000.0;
    let mut result = FileScanResult::default();
    let cli_root = source_path.parent().unwrap_or_else(|| Path::new(""));
    let mut session_events = load_cli_session_events(cli_root);
    result.scanned_lines += session_events
        .values()
        .map(|events| events.scanned_lines)
        .sum::<usize>();
    let query =
        "SELECT u.session_id, u.turn_index, u.model, u.total_nano_aiu,
                u.duration_ms, u.created_at, u.agent_id
         FROM assistant_usage_events u
         WHERE u.total_nano_aiu IS NOT NULL AND u.total_nano_aiu > 0
         ORDER BY u.session_id, u.turn_index, u.model, u.created_at, u.id";
    let mut statement = connection.prepare(query)?;
    let rows = statement.query_map([], |row| {
        Ok((
            row.get::<_, String>(0)?,
            row.get::<_, Option<i64>>(1)?,
            row.get::<_, String>(2)?,
            row.get::<_, i64>(3)?,
            row.get::<_, Option<i64>>(4)?,
            row.get::<_, String>(5)?,
            row.get::<_, Option<String>>(6)?,
        ))
    })?;

    let mut aggregates: BTreeMap<(String, Option<u32>, String), CliUsageAggregate> =
        BTreeMap::new();
    let mut sessions_with_database_usage = HashSet::new();
    for row in rows {
        result.scanned_lines += 1;
        result.json_candidate_lines += 1;
        let (
            session_id,
            zero_based_turn,
            model,
            total_nano_aiu,
            duration_ms,
            created_at,
            agent_id,
        ) = row?;
        let Some(completed_at_ms) = parse_rfc3339_timestamp_ms(&created_at) else {
            result.parse_errors += 1;
            continue;
        };
        let Some((record_source_path, record_source_line, event_timestamp_ms)) =
            match_cli_event_message(
            &mut session_events,
            &session_id,
            completed_at_ms,
            &model,
            agent_id_is_present(&agent_id),
        )
        else {
            continue;
        };
        sessions_with_database_usage.insert(session_id.clone());
        if cutoff_ms.is_some_and(|cutoff| event_timestamp_ms < cutoff) {
            continue;
        }

        let (title, project) = session_events
            .get(&session_id)
            .map(|events| (events.title.clone(), events.project.clone()))
            .unwrap_or_default();
        let turn_index = zero_based_turn.and_then(|turn| {
            turn.checked_add(1)
                .and_then(|turn| u32::try_from(turn).ok())
        });
        let key = (session_id.clone(), turn_index, model.clone());
        let duration_ms = duration_ms.unwrap_or_default().max(0);
        let started_at_ms = event_timestamp_ms.saturating_sub(duration_ms);

        let entry = aggregates.entry(key).or_insert_with(|| CliUsageAggregate {
            source_path: record_source_path.clone(),
            source_line: record_source_line,
            session_id,
            turn_index,
            model,
            credits: 0.0,
            request_count: 0,
            started_at_ms,
            completed_at_ms: event_timestamp_ms,
            title: title.clone(),
            project: project.clone(),
        });
        if record_source_line < entry.source_line {
            entry.source_path = record_source_path;
            entry.source_line = record_source_line;
        }
        entry.credits += total_nano_aiu as f64 / NANO_AIU_PER_CREDIT;
        entry.request_count += 1;
        entry.started_at_ms = entry.started_at_ms.min(started_at_ms);
        entry.completed_at_ms = entry.completed_at_ms.max(event_timestamp_ms);
        if entry.title.is_none() {
            entry.title = title;
        }
        if entry.project.is_none() {
            entry.project = project;
        }
    }

    let mut session_totals: HashMap<String, u32> = HashMap::new();
    for aggregate in aggregates.values() {
        if let Some(turn) = aggregate.turn_index {
            session_totals
                .entry(aggregate.session_id.clone())
                .and_modify(|total| *total = (*total).max(turn))
                .or_insert(turn);
        }
    }

    for aggregate in aggregates.into_values() {
        let duration_ms = aggregate
            .completed_at_ms
            .saturating_sub(aggregate.started_at_ms);
        let details = format!(
            "Copilot CLI {} ({} model call{}) • {} credits",
            aggregate.model,
            aggregate.request_count,
            if aggregate.request_count == 1 {
                ""
            } else {
                "s"
            },
            aggregate.credits
        );
        result.records.push(UsageRecord {
            source: "copilot.cli.events".to_owned(),
            hostname: String::new(),
            timestamp_ms: Some(aggregate.completed_at_ms),
            local_time_hint: format_local_time(aggregate.completed_at_ms),
            chat_title: aggregate.title,
            model: aggregate.model.clone(),
            model_id: Some(aggregate.model),
            credits: aggregate.credits,
            details,
            session_id: Some(aggregate.session_id.clone()),
            request_id: None,
            response_id: None,
            agent_id: None,
            project: aggregate.project,
            duration_ms: (duration_ms > 0).then_some(duration_ms),
            turn_index: aggregate.turn_index,
            session_total: session_totals.get(&aggregate.session_id).copied(),
            file: aggregate.source_path.to_string_lossy().into_owned(),
            line: aggregate.source_line,
        });
    }

    append_legacy_cli_shutdown_records(
        &mut result,
        &session_events,
        &sessions_with_database_usage,
        cutoff_ms,
    );

    Ok(result)
}

fn agent_id_is_present(agent_id: &Option<String>) -> bool {
    agent_id.as_ref().is_some_and(|agent| !agent.is_empty())
}

fn load_cli_session_events(root: &Path) -> HashMap<String, CliSessionEvents> {
    let session_root = root.join("session-state");
    let Ok(entries) = fs::read_dir(session_root) else {
        return HashMap::new();
    };
    let mut sessions = HashMap::new();
    for entry in entries.flatten() {
        let Ok(file_type) = entry.file_type() else {
            continue;
        };
        if !file_type.is_dir() {
            continue;
        }
        let session_id = entry.file_name().to_string_lossy().into_owned();
        let path = entry.path().join("events.jsonl");
        if let Some(events) = read_cli_session_events(&path) {
            sessions.insert(session_id, events);
        }
    }
    sessions
}

fn read_cli_session_events(path: &Path) -> Option<CliSessionEvents> {
    let file = File::open(path).ok()?;
    let workspace = path
        .parent()
        .map(read_cli_workspace_metadata)
        .unwrap_or_default();
    let mut events = CliSessionEvents {
        path: path.to_path_buf(),
        title: workspace.title,
        project: workspace.project,
        ..CliSessionEvents::default()
    };
    let reader = BufReader::with_capacity(1024 * 1024, file);
    for (index, line) in reader.split(b'\n').enumerate() {
        events.scanned_lines += 1;
        let Ok(line) = line else {
            continue;
        };
        let Ok(value) = serde_json::from_slice::<Value>(&line) else {
            continue;
        };
        let Some(object) = value.as_object() else {
            continue;
        };
        let Some(timestamp_ms) = object
            .get("timestamp")
            .and_then(Value::as_str)
            .and_then(parse_rfc3339_timestamp_ms)
        else {
            continue;
        };
        let line_number = index + 1;
        let event_type = object.get("type").and_then(Value::as_str);
        let data = object.get("data").and_then(Value::as_object);
        if event_type == Some("user.message") && events.title.is_none() {
            let is_root_user_message = object
                .get("agentId")
                .and_then(Value::as_str)
                .is_none_or(str::is_empty)
                && data
                    .and_then(|data| data.get("source"))
                    .is_none_or(Value::is_null);
            if is_root_user_message {
                events.title = data
                    .and_then(|data| data.get("content"))
                    .and_then(Value::as_str)
                    .and_then(|content| normalized_cli_title(Some(content)));
            }
        } else if event_type == Some("assistant.message") {
            let Some(data) = data else {
                continue;
            };
            let Some(model) = data.get("model").and_then(Value::as_str) else {
                continue;
            };
            let Some(api_call_id) = data.get("apiCallId").and_then(Value::as_str) else {
                continue;
            };
            events.messages.push(CliEventMessage {
                line: line_number,
                timestamp_ms,
                model: model.to_owned(),
                is_subagent: object
                    .get("agentId")
                    .and_then(Value::as_str)
                    .is_some_and(|agent| !agent.is_empty()),
                api_call_id: api_call_id.to_owned(),
            });
        } else if event_type == Some("session.shutdown") {
            let Some(model_metrics) = data
                .and_then(|data| data.get("modelMetrics"))
                .and_then(Value::as_object)
            else {
                continue;
            };
            for (model, metrics) in model_metrics {
                let Some(credits) = metrics
                    .get("requests")
                    .and_then(|requests| requests.get("cost"))
                    .and_then(value_as_f64)
                else {
                    continue;
                };
                if credits > 0.0 {
                    events.shutdown_metrics.push(CliShutdownMetric {
                        line: line_number,
                        timestamp_ms,
                        model: model.clone(),
                        credits,
                    });
                }
            }
        }
    }
    Some(events)
}

fn read_cli_workspace_metadata(session_dir: &Path) -> CliWorkspaceMetadata {
    let Ok(workspace) = fs::read_to_string(session_dir.join("workspace.yaml")) else {
        return CliWorkspaceMetadata::default();
    };
    let mut name = None;
    let mut cwd = None;
    for line in workspace.lines().filter(|line| !line.starts_with(char::is_whitespace)) {
        if let Some(value) = line.strip_prefix("name:").and_then(cli_yaml_scalar) {
            name = Some(value);
        } else if let Some(value) = line.strip_prefix("cwd:").and_then(cli_yaml_scalar) {
            cwd = Some(value);
        }
    }
    CliWorkspaceMetadata {
        title: name.as_deref().and_then(|name| normalized_cli_title(Some(name))),
        project: cwd.as_deref().and_then(project_name_from_cli_path),
    }
}

fn cli_yaml_scalar(raw: &str) -> Option<String> {
    let value = raw.trim();
    if value.is_empty() {
        return None;
    }
    if value.starts_with('"') && value.ends_with('"') {
        return serde_json::from_str::<String>(value).ok();
    }
    let value = value
        .strip_prefix('\'')
        .and_then(|value| value.strip_suffix('\''))
        .unwrap_or(value)
        .replace("''", "'");
    (!value.is_empty()).then_some(value)
}

fn match_cli_event_message(
    sessions: &mut HashMap<String, CliSessionEvents>,
    session_id: &str,
    timestamp_ms: i64,
    model: &str,
    is_subagent: bool,
) -> Option<(PathBuf, usize, i64)> {
    const MAX_TIMESTAMP_DELTA_MS: i64 = 1_000;
    let events = sessions.get_mut(session_id)?;
    let find_nearest = |require_agent_match: bool, events: &CliSessionEvents| {
        events
            .messages
            .iter()
            .enumerate()
            .filter(|(_, message)| {
                message.model == model
                    && !events.used_api_calls.contains(&message.api_call_id)
                    && (!require_agent_match || message.is_subagent == is_subagent)
            })
            .min_by_key(|(_, message)| message.timestamp_ms.abs_diff(timestamp_ms))
            .map(|(index, message)| (index, message.timestamp_ms.abs_diff(timestamp_ms)))
    };
    let (index, delta) = find_nearest(true, events).or_else(|| find_nearest(false, events))?;
    if delta > u64::try_from(MAX_TIMESTAMP_DELTA_MS).ok()? {
        return None;
    }
    let message = &events.messages[index];
    events.used_api_calls.insert(message.api_call_id.clone());
    Some((events.path.clone(), message.line, message.timestamp_ms))
}

fn append_legacy_cli_shutdown_records(
    result: &mut FileScanResult,
    session_events: &HashMap<String, CliSessionEvents>,
    sessions_with_database_usage: &HashSet<String>,
    cutoff_ms: Option<i64>,
) {
    for (session_id, events) in session_events {
        if sessions_with_database_usage.contains(session_id) {
            continue;
        }
        for metric in &events.shutdown_metrics {
            if cutoff_ms.is_some_and(|cutoff| metric.timestamp_ms < cutoff) {
                continue;
            }
            result.json_candidate_lines += 1;
            result.records.push(UsageRecord {
                source: "copilot.cli.events".to_owned(),
                hostname: String::new(),
                timestamp_ms: Some(metric.timestamp_ms),
                local_time_hint: format_local_time(metric.timestamp_ms),
                chat_title: events.title.clone(),
                model: metric.model.clone(),
                model_id: Some(metric.model.clone()),
                credits: metric.credits,
                details: format!(
                    "Copilot CLI {} (legacy session shutdown) • {} credits",
                    metric.model, metric.credits
                ),
                session_id: Some(session_id.clone()),
                request_id: None,
                response_id: None,
                agent_id: None,
                project: events.project.clone(),
                duration_ms: None,
                turn_index: None,
                session_total: None,
                file: events.path.to_string_lossy().into_owned(),
                line: metric.line,
            });
        }
    }
}

fn system_time_to_unix_ms(time: &std::time::SystemTime) -> Option<i64> {
    let millis = time.duration_since(std::time::UNIX_EPOCH).ok()?.as_millis();
    i64::try_from(millis).ok()
}

fn project_name_from_cli_path(path: &str) -> Option<String> {
    path.trim()
        .trim_end_matches(['/', '\\'])
        .rsplit(['/', '\\'])
        .find(|part| !part.trim().is_empty())
        .map(str::trim)
        .filter(|part| !part.is_empty())
        .map(ToOwned::to_owned)
}

fn normalized_cli_title(value: Option<&str>) -> Option<String> {
    let value = value?.lines().find(|line| !line.trim().is_empty())?.trim();
    if value.is_empty() {
        return None;
    }
    const MAX_CHARS: usize = 120;
    let mut title: String = value.chars().take(MAX_CHARS).collect();
    if value.chars().count() > MAX_CHARS {
        title.push('…');
    }
    Some(title)
}

fn has_component(path: &Path, wanted: &str) -> bool {
    path.components().any(|component| {
        component
            .as_os_str()
            .to_string_lossy()
            .eq_ignore_ascii_case(wanted)
    })
}

fn modified_after(path: &Path, cutoff: Option<&std::time::SystemTime>) -> bool {
    match cutoff {
        Some(cutoff) => path
            .metadata()
            .and_then(|metadata| metadata.modified())
            .is_ok_and(|modified| modified >= *cutoff),
        None => true,
    }
}

fn scan_file(path: &Path, project_map: &HashMap<PathBuf, String>) -> FileScanResult {
    if has_component(path, "chatSessions") {
        let project = workspace_dir_for_session(path)
            .and_then(|dir| project_map.get(&dir).cloned());
        return vscode::scan(path, project);
    }
    let mut result = FileScanResult::default();

    let Ok(file) = File::open(path) else {
        result.parse_errors += 1;
        return result;
    };

    let source = if has_component(path, "chatSessions") {
        "vscode.chatSessions"
    } else {
        "copilot.cli.probe"
    };

    let cli_workspace = (source == "copilot.cli.probe")
        .then(|| path.parent())
        .flatten()
        .map(read_cli_workspace_metadata)
        .unwrap_or_default();
    let project = workspace_dir_for_session(path)
        .and_then(|dir| project_map.get(&dir).cloned())
        .or(cli_workspace.project);
    let cli_session_id = (source == "copilot.cli.probe")
        .then(|| cli_session_id_from_event_path(path))
        .flatten();

    let mut reader = BufReader::with_capacity(1024 * 1024, file);
    let mut custom_title = cli_workspace.title;
    let mut weak_title: Option<String> = None;
    // VS Code chatSessions JSONL is a state-change log, not an append-only
    // event ledger. The same request result can be persisted repeatedly as
    // later mutations overwrite `requests[index].result`. Keep one logical
    // usage record per stable response identity and update it to the latest
    // persisted state instead of charging every physical JSONL line.
    let mut vscode_response_records: HashMap<String, usize> = HashMap::new();
    let mut line_index = 0usize;
    let mut line = Vec::with_capacity(16 * 1024);

    loop {
        line.clear();
        let bytes_read = match reader.read_until(b'\n', &mut line) {
            Ok(bytes_read) => bytes_read,
            Err(_) => {
                result.parse_errors += 1;
                break;
            }
        };
        if bytes_read == 0 {
            break;
        }

        line_index += 1;
        result.scanned_lines += 1;

        // Title resolution: the authoritative session name is `customTitle`.
        // Scan the header window for it and only fall back to a plain `title`
        // when no customTitle exists anywhere, so an early JSON-schema title
        // (e.g. the model's "Thinking Effort" label) can never win.
        if custom_title.is_none()
            && source == "copilot.cli.probe"
            && let Some(title) = extract_cli_user_title_from_line(&line)
        {
            custom_title = Some(title);
        } else if custom_title.is_none() && line_index <= 64 {
            if let Some(title) = extract_custom_title_from_line(&line) {
                custom_title = Some(title);
            } else if weak_title.is_none()
                && let Some(title) = extract_weak_title_from_line(&line)
            {
                weak_title = Some(title);
            }
        }

        if !is_usage_candidate_line(source, &line) {
            continue;
        }

        result.json_candidate_lines += 1;

        match serde_json::from_slice::<Value>(&line) {
            Ok(value) => {
                let mut extraction = LineExtraction::default();
                collect_line_extraction(&value, ContextFields::default(), &mut extraction);
                for raw in extraction.records {
                    let local =
                        enrich_from_response_metadata(raw.context, &extraction.response_metadata);
                    let record = UsageRecord {
                        source: source.to_owned(),
                        hostname: String::new(),
                        timestamp_ms: local.timestamp_ms,
                        local_time_hint: local.timestamp_ms.and_then(format_local_time),
                        chat_title: None,
                        model: raw.model,
                        model_id: local.model_id.as_deref().map(display_model_id),
                        credits: raw.credits,
                        details: raw.details,
                        session_id: local.session_id.clone().or_else(|| cli_session_id.clone()),
                        request_id: local.request_id.clone(),
                        response_id: local.response_id.clone(),
                        agent_id: local.agent_id.clone(),
                        project: project.clone(),
                        duration_ms: local.total_elapsed_ms,
                        turn_index: None,
                        session_total: None,
                        file: path.to_string_lossy().into_owned(),
                        line: line_index,
                    };
                    store_scanned_record(&mut result.records, &mut vscode_response_records, record);
                }
            }
            Err(_) => {
                result.parse_errors += 1;
                if let Ok(text) = std::str::from_utf8(&line) {
                    collect_records_from_text(source, path, line_index, text, &mut result.records);
                }
            }
        }
    }

    if let Some(title) = custom_title.or(weak_title) {
        for record in &mut result.records {
            record.chat_title = Some(title.clone());
        }
    }

    result
}

fn store_scanned_record(
    records: &mut Vec<UsageRecord>,
    vscode_response_records: &mut HashMap<String, usize>,
    record: UsageRecord,
) {
    if record.source == "vscode.chatSessions"
        && let Some(response_id) = record.response_id.clone()
    {
        if let Some(index) = vscode_response_records.get(&response_id).copied() {
            records[index] = record;
        } else {
            vscode_response_records.insert(response_id, records.len());
            records.push(record);
        }
    } else {
        records.push(record);
    }
}

fn cli_session_id_from_event_path(path: &Path) -> Option<String> {
    if !path
        .file_name()
        .is_some_and(|name| name.eq_ignore_ascii_case("events.jsonl"))
    {
        return None;
    }
    let session_dir = path.parent()?;
    let session_root = session_dir.parent()?;
    if !session_root
        .file_name()
        .is_some_and(|name| name.eq_ignore_ascii_case("session-state"))
    {
        return None;
    }
    session_dir
        .file_name()
        .map(|session_id| session_id.to_string_lossy().into_owned())
}

fn contains_bytes(haystack: &[u8], needle: &[u8]) -> bool {
    memmem::find(haystack, needle).is_some()
}

fn is_usage_candidate_line(source: &str, line: &[u8]) -> bool {
    if contains_bytes(line, b"credits") && contains_bytes(line, b"details") {
        return true;
    }

    source == "copilot.cli.probe"
        && contains_bytes(line, b"session.shutdown")
        && contains_bytes(line, b"modelMetrics")
}

fn collect_line_extraction(value: &Value, context: ContextFields, extraction: &mut LineExtraction) {
    match value {
        Value::Array(items) => {
            for item in items {
                collect_line_extraction(item, context.clone(), extraction);
            }
        }
        Value::Object(map) => {
            let mut local = context.clone();
            merge_context_from_object(&mut local, map);
            if let Some(Value::Object(metadata)) = map.get("metadata") {
                merge_context_from_object(&mut local, metadata);
            }

            if let Some(response_id) = local.response_id.clone() {
                let entry = extraction.response_metadata.entry(response_id).or_default();
                merge_context_missing(entry, &local);
            }

            if let Some(details) = map.get("details").and_then(Value::as_str)
                && let Some((model, credits)) = parse_credit_details(details)
            {
                extraction.records.push(RawUsageRecord {
                    context: local.clone(),
                    model,
                    credits,
                    details: details.to_owned(),
                });
            }

            collect_cli_shutdown_metrics(map, &local, extraction);

            for child in map.values() {
                collect_line_extraction(child, local.clone(), extraction);
            }
        }
        _ => {}
    }
}

fn collect_cli_shutdown_metrics(
    map: &serde_json::Map<String, Value>,
    context: &ContextFields,
    extraction: &mut LineExtraction,
) {
    if map.get("type").and_then(Value::as_str) != Some("session.shutdown") {
        return;
    }

    let Some(model_metrics) = map
        .get("data")
        .and_then(|data| data.get("modelMetrics"))
        .and_then(Value::as_object)
    else {
        return;
    };

    for (model, metrics) in model_metrics {
        let Some(credits) = metrics
            .get("requests")
            .and_then(|requests| requests.get("cost"))
            .and_then(value_as_f64)
        else {
            continue;
        };

        extraction.records.push(RawUsageRecord {
            context: context.clone(),
            model: model.clone(),
            credits,
            details: format!("Copilot CLI {model} • {credits} credits"),
        });
    }
}

fn value_as_f64(value: &Value) -> Option<f64> {
    match value {
        Value::Number(number) => number.as_f64(),
        _ => None,
    }
}

/// Returns the workspaceStorage/<hash> directory that owns a chatSessions file:
/// `.../workspaceStorage/<hash>/chatSessions/<id>.jsonl` -> `.../workspaceStorage/<hash>`.
fn workspace_dir_for_session(path: &Path) -> Option<PathBuf> {
    let chat_sessions = path.parent()?;
    if !chat_sessions
        .file_name()
        .is_some_and(|name| name.eq_ignore_ascii_case("chatSessions"))
    {
        return None;
    }
    Some(chat_sessions.parent()?.to_path_buf())
}

/// Reads each workspace's `workspace.json` once and maps the storage directory
/// to a friendly project name (the last segment of the opened folder/workspace).
fn build_project_map(files: &[PathBuf]) -> HashMap<PathBuf, String> {
    let mut map: HashMap<PathBuf, String> = HashMap::new();
    let mut dirs: std::collections::BTreeSet<PathBuf> = std::collections::BTreeSet::new();
    for file in files {
        if let Some(dir) = workspace_dir_for_session(file) {
            dirs.insert(dir);
        }
    }
    for dir in dirs {
        if let Some(name) = read_project_name(&dir) {
            map.insert(dir, name);
        }
    }
    map
}

fn read_project_name(workspace_dir: &Path) -> Option<String> {
    let text = fs::read_to_string(workspace_dir.join("workspace.json")).ok()?;
    let value: Value = serde_json::from_str(&text).ok()?;
    let object = value.as_object()?;
    if let Some(folder) = object.get("folder").and_then(Value::as_str) {
        return project_name_from_uri(folder, false);
    }
    if let Some(workspace) = object.get("workspace").and_then(Value::as_str) {
        return project_name_from_uri(workspace, true);
    }
    None
}

/// Extracts a human-readable project name from a VS Code file URI.
/// `file:///c%3A/Scripts/projects/opendecknew` -> `opendecknew`.
/// A `.code-workspace` file URI returns the file stem.
fn project_name_from_uri(uri: &str, is_workspace_file: bool) -> Option<String> {
    let without_scheme = uri.strip_prefix("file://").unwrap_or(uri);
    let decoded = percent_decode(without_scheme);
    let trimmed = decoded.trim_end_matches(['/', '\\']);
    let last = trimmed
        .rsplit(['/', '\\'])
        .find(|segment| !segment.is_empty())?;
    let name = if is_workspace_file {
        last.strip_suffix(".code-workspace").unwrap_or(last)
    } else {
        last
    }
    .trim();
    if name.is_empty() {
        None
    } else {
        Some(name.to_owned())
    }
}

/// Minimal percent-decoding sufficient for VS Code workspace URIs.
fn percent_decode(input: &str) -> String {
    let bytes = input.as_bytes();
    let mut out: Vec<u8> = Vec::with_capacity(bytes.len());
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index] == b'%' && index + 2 < bytes.len() {
            let hi = (bytes[index + 1] as char).to_digit(16);
            let lo = (bytes[index + 2] as char).to_digit(16);
            if let (Some(hi), Some(lo)) = (hi, lo) {
                out.push((hi * 16 + lo) as u8);
                index += 3;
                continue;
            }
        }
        out.push(bytes[index]);
        index += 1;
    }
    String::from_utf8_lossy(&out).into_owned()
}

/// Assigns a 1-based `turn_index` within each parent session plus the session's
/// total exchange count. Records must already be ordered chronologically within
/// each `(hostname, session_id)` group, which both the scan and merge sorts
/// guarantee.
fn assign_turn_indices(records: &mut [UsageRecord]) {
    // Replayed VS Code and SQLite-backed CLI records carry user-facing turns.
    // Preserve those values; only synthesize sequential positions for legacy
    // VS Code/CLI records where no turn was recorded at all.
    let mut explicit_totals: HashMap<(String, String), u32> = HashMap::new();
    let mut implicit_totals: HashMap<(String, String), u32> = HashMap::new();
    for record in records.iter() {
        if is_cli_session_summary(record) {
            continue;
        }
        if let Some(session) = record.session_id.as_ref() {
            let key = (record.hostname.clone(), session.clone());
            if let Some(turn) = record.turn_index {
                let known_total = record.session_total.unwrap_or(turn).max(turn);
                explicit_totals
                    .entry(key)
                    .and_modify(|total| *total = (*total).max(known_total))
                    .or_insert(known_total);
            } else {
                *implicit_totals.entry(key).or_default() += 1;
            }
        }
    }
    let mut seen: HashMap<(String, String), u32> = HashMap::new();
    for record in records.iter_mut() {
        if is_cli_session_summary(record) {
            record.turn_index = None;
            record.session_total = None;
            continue;
        }
        let Some(session) = record.session_id.clone() else {
            record.turn_index = None;
            record.session_total = None;
            continue;
        };
        let key = (record.hostname.clone(), session);
        if record.turn_index.is_some() {
            record.session_total = explicit_totals.get(&key).copied();
            continue;
        }
        let counter = seen.entry(key.clone()).or_default();
        *counter += 1;
        record.turn_index = Some(*counter);
        record.session_total = implicit_totals.get(&key).copied();
    }
}

fn is_cli_session_summary(record: &UsageRecord) -> bool {
    record.source.starts_with("copilot.cli")
        && (record.details.contains("legacy session shutdown")
            || (record.source == "copilot.cli.probe" && record.request_id.is_none()))
}

fn merge_context_from_object(context: &mut ContextFields, map: &serde_json::Map<String, Value>) {
    assign_string(&mut context.session_id, map, "sessionId");
    assign_string(&mut context.request_id, map, "requestId");
    assign_string(&mut context.response_id, map, "responseId");
    assign_string(&mut context.model_id, map, "modelId");
    assign_string(&mut context.agent_id, map, "agentId");

    if context.timestamp_ms.is_none() {
        context.timestamp_ms = map.get("timestamp").and_then(|value| {
            value
                .as_i64()
                .or_else(|| value.as_str().and_then(parse_rfc3339_timestamp_ms))
        });
    }

    if let Some(Value::Object(model_state)) = map.get("modelState")
        && let Some(completed_at) = model_state.get("completedAt").and_then(Value::as_i64)
    {
        context.timestamp_ms = Some(completed_at);
    }

    if let Some(completed_at) = map.get("completedAt").and_then(Value::as_i64) {
        context.timestamp_ms = Some(completed_at);
    }

    // The chat-session `result` node carries wall-clock timing for the whole
    // exchange (request submitted -> response completed) under `timings`.
    if context.total_elapsed_ms.is_none()
        && let Some(Value::Object(timings)) = map.get("timings")
        && let Some(elapsed) = timings.get("totalElapsed").and_then(Value::as_i64)
        && elapsed > 0
    {
        context.total_elapsed_ms = Some(elapsed);
    }
}

fn parse_rfc3339_timestamp_ms(timestamp: &str) -> Option<i64> {
    DateTime::parse_from_rfc3339(timestamp)
        .ok()
        .map(|time| time.timestamp_millis())
}

fn assign_string(target: &mut Option<String>, map: &serde_json::Map<String, Value>, key: &str) {
    if target.is_none()
        && let Some(value) = map.get(key).and_then(Value::as_str)
    {
        *target = Some(value.to_owned());
    }
}

fn parse_credit_details(details: &str) -> Option<(String, f64)> {
    let trimmed = details.trim();
    let before_suffix = trimmed
        .strip_suffix(" credits")
        .or_else(|| trimmed.strip_suffix(" credit"))?;
    let mut parts = before_suffix.rsplitn(2, char::is_whitespace);
    let credits_text = parts.next()?.trim();
    let model_part = parts.next()?.trim();

    let credits = credits_text.parse::<f64>().ok()?;
    let model = model_part
        .trim_end_matches(|ch: char| {
            ch.is_whitespace() || !(ch.is_ascii_alphanumeric() || ch == ')' || ch == ']')
        })
        .trim()
        .to_owned();

    if model.is_empty() || !credits.is_finite() || credits < 0.0 {
        None
    } else {
        Some((model, credits))
    }
}

fn display_model_id(model_id: &str) -> String {
    model_id
        .strip_prefix("copilot/")
        .unwrap_or(model_id)
        .to_owned()
}

fn format_local_time(timestamp_ms: i64) -> Option<String> {
    let utc = DateTime::<Utc>::from_timestamp_millis(timestamp_ms)?;
    Some(
        utc.with_timezone(&Local)
            .format("%Y-%m-%d %H:%M:%S")
            .to_string(),
    )
}

fn format_local_day(timestamp_ms: i64) -> Option<String> {
    let utc = DateTime::<Utc>::from_timestamp_millis(timestamp_ms)?;
    Some(utc.with_timezone(&Local).format("%Y-%m-%d").to_string())
}

fn collect_records_from_text(
    source: &str,
    path: &Path,
    line_number: usize,
    line: &str,
    records: &mut Vec<UsageRecord>,
) {
    let Some(details_key_index) = line.find("details") else {
        return;
    };
    let Some(credits_index) = line[details_key_index..].find("credits") else {
        return;
    };

    let end = details_key_index + credits_index + "credits".len();
    let start = line[..details_key_index]
        .rfind('"')
        .map(|index| index + 1)
        .unwrap_or(details_key_index);
    let candidate = &line[start..end];

    if let Some((model, credits)) = parse_credit_details(candidate) {
        records.push(UsageRecord {
            source: source.to_owned(),
            hostname: String::new(),
            timestamp_ms: None,
            local_time_hint: None,
            chat_title: None,
            model,
            model_id: None,
            credits,
            details: candidate.to_owned(),
            session_id: None,
            request_id: None,
            response_id: None,
            agent_id: None,
            project: None,
            duration_ms: None,
            turn_index: None,
            session_total: None,
            file: path.to_string_lossy().into_owned(),
            line: line_number,
        });
    }
}

fn write_csv(path: &Path, records: &[UsageRecord], emit_bom: bool) -> Result<()> {
    if path.as_os_str() == "-" {
        let mut writer = csv::Writer::from_writer(std::io::stdout());
        for record in records {
            writer.serialize(record)?;
        }
        writer.flush()?;
        return Ok(());
    }

    let mut file = File::create(path)
        .with_context(|| format!("failed to create CSV output {}", path.display()))?;
    if emit_bom {
        file.write_all(b"\xEF\xBB\xBF")?;
    }

    let mut writer = csv::Writer::from_writer(file);
    for record in records {
        writer.serialize(record)?;
    }
    writer.flush()?;
    Ok(())
}

fn write_json(path: &Path, records: &[UsageRecord], emit_bom: bool) -> Result<()> {
    if path.as_os_str() == "-" {
        println!("{}", serde_json::to_string_pretty(records)?);
        return Ok(());
    }

    let mut file = File::create(path)
        .with_context(|| format!("failed to create JSON output {}", path.display()))?;
    if emit_bom {
        file.write_all(b"\xEF\xBB\xBF")?;
    }
    serde_json::to_writer_pretty(file, records)?;
    Ok(())
}

fn enrich_from_response_metadata(
    mut local: ContextFields,
    response_metadata: &HashMap<String, ContextFields>,
) -> ContextFields {
    if let Some(response_id) = local.response_id.as_ref()
        && let Some(metadata) = response_metadata.get(response_id)
    {
        merge_context_missing(&mut local, metadata);
    }
    local
}

fn merge_context_missing(target: &mut ContextFields, source: &ContextFields) {
    if target.session_id.is_none() {
        target.session_id = source.session_id.clone();
    }
    if target.request_id.is_none() {
        target.request_id = source.request_id.clone();
    }
    if target.response_id.is_none() {
        target.response_id = source.response_id.clone();
    }
    if target.model_id.is_none() {
        target.model_id = source.model_id.clone();
    }
    if target.agent_id.is_none() {
        target.agent_id = source.agent_id.clone();
    }
    if target.timestamp_ms.is_none() {
        target.timestamp_ms = source.timestamp_ms;
    }
    if target.total_elapsed_ms.is_none() {
        target.total_elapsed_ms = source.total_elapsed_ms;
    }
}

fn extract_custom_title(value: &Value) -> Option<String> {
    let object = value.as_object()?;
    let key = object.get("k")?.as_array()?;
    let is_custom_title = key
        .iter()
        .any(|part| part.as_str().is_some_and(|text| text == "customTitle"));
    if !is_custom_title {
        return None;
    }

    object
        .get("v")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|title| !title.is_empty())
        .map(ToOwned::to_owned)
}

/// Best-effort byte-level scan for the chat title without parsing the entire
/// session document. Handles both shapes we have seen:
///   - delta jsonl header   : {"k":["customTitle"],"v":"…"}
///   - single-object session: {"kind":0,"v":{"customTitle":"…", "title":"…", …}}
#[cfg(test)]
fn quick_extract_title_from_line(line: &[u8]) -> Option<String> {
    const NEEDLES: [&[u8]; 2] = [b"\"customTitle\":\"", b"\"title\":\""];
    for needle in NEEDLES {
        if let Some(title) = extract_json_string_after(line, needle) {
            return Some(title);
        }
    }
    None
}

/// Walks the bytes after `needle` (which must end at the opening quote of a JSON
/// string) and decodes the first complete JSON string literal that follows.
fn extract_json_string_after(line: &[u8], needle: &[u8]) -> Option<String> {
    let mut search_from = 0;
    while let Some(rel) = memmem::find(&line[search_from..], needle) {
        let start = search_from + rel;
        // Include the opening quote so serde_json can decode the literal.
        let literal_start = start + needle.len() - 1;
        let mut cursor = literal_start + 1;
        while cursor < line.len() {
            let byte = line[cursor];
            if byte == b'\\' {
                cursor += 2;
                continue;
            }
            if byte == b'"' {
                break;
            }
            cursor += 1;
        }
        if cursor >= line.len() {
            break;
        }
        let literal = &line[literal_start..=cursor];
        if let Ok(text) = std::str::from_utf8(literal)
            && let Ok(decoded) = serde_json::from_str::<String>(text)
        {
            let trimmed = decoded.trim();
            if !trimmed.is_empty() {
                return Some(trimmed.to_owned());
            }
        }
        search_from = cursor + 1;
    }
    None
}

/// Extracts the authoritative session `customTitle` from a single line, covering
/// both the inline (`"customTitle":"…"`) and delta (`{"k":["customTitle"],"v":…}`)
/// shapes.
fn extract_custom_title_from_line(line: &[u8]) -> Option<String> {
    if let Some(title) = extract_json_string_after(line, b"\"customTitle\":\"") {
        return Some(title);
    }
    if contains_bytes(line, b"customTitle")
        && let Ok(value) = serde_json::from_slice::<Value>(line)
        && let Some(title) = extract_custom_title(&value)
    {
        return Some(title);
    }
    None
}

fn extract_cli_user_title_from_line(line: &[u8]) -> Option<String> {
    if !contains_bytes(line, b"user.message") || !contains_bytes(line, b"content") {
        return None;
    }
    let value = serde_json::from_slice::<Value>(line).ok()?;
    let object = value.as_object()?;
    if object.get("type").and_then(Value::as_str) != Some("user.message")
        || object
            .get("agentId")
            .and_then(Value::as_str)
            .is_some_and(|agent| !agent.is_empty())
    {
        return None;
    }
    let data = object.get("data")?.as_object()?;
    if data.get("source").is_some_and(|source| !source.is_null()) {
        return None;
    }
    normalized_cli_title(data.get("content").and_then(Value::as_str))
}

/// Extracts a plain `"title"` as a weak fallback, skipping JSON-schema lines
/// (e.g. a model's `{"reasoningEffort":{"title":"Thinking Effort","enum":[…]}}`)
/// whose `title` is a UI label, not the session title.
fn extract_weak_title_from_line(line: &[u8]) -> Option<String> {
    if contains_bytes(line, b"\"enum\"")
        || contains_bytes(line, b"\"properties\"")
        || contains_bytes(line, b"reasoningEffort")
    {
        return None;
    }
    extract_json_string_after(line, b"\"title\":\"")
}

fn detect_hostname() -> String {
    if let Some(name) = env::var("COMPUTERNAME")
        .ok()
        .or_else(|| env::var("HOSTNAME").ok())
        .map(|name| sanitize_hostname(&name))
        .filter(|name| !name.is_empty())
    {
        return name;
    }

    #[cfg(unix)]
    {
        for path in ["/proc/sys/kernel/hostname", "/etc/hostname"] {
            if let Ok(text) = fs::read_to_string(path) {
                let cleaned = sanitize_hostname(&text);
                if !cleaned.is_empty() {
                    return cleaned;
                }
            }
        }
    }

    "unknown-host".to_owned()
}

fn sanitize_hostname(raw: &str) -> String {
    raw.trim()
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' || ch == '.' {
                ch
            } else {
                '-'
            }
        })
        .collect::<String>()
        .trim_matches('-')
        .to_owned()
}

fn default_output_path(hostname: &str, format: OutputFormat) -> PathBuf {
    let extension = match format {
        OutputFormat::Csv => "csv",
        OutputFormat::Json => "json",
    };
    PathBuf::from(format!("copilot-usage-{hostname}.{extension}"))
}

fn default_html_path(output_path: &Path, hostname: &str) -> PathBuf {
    // Place the HTML next to the primary output file, replacing the extension.
    let mut candidate = output_path.to_path_buf();
    if candidate.set_extension("html") {
        return candidate;
    }
    PathBuf::from(format!("copilot-usage-{hostname}.html"))
}

const REPORT_TEMPLATE: &str = include_str!("report-template.html");
const REPORT_DATA_PLACEHOLDER: &str = "__GH_USAGE_DATA__";
const REPORT_SNAPDOM: &str = include_str!("snapdom.js");
const REPORT_SNAPDOM_PLACEHOLDER: &str = "__GH_USAGE_SNAPDOM__";

fn write_html(path: &Path, records: &[UsageRecord], primary_host: &str) -> Result<()> {
    let payload = serde_json::json!({
        "generatedAt": Local::now().format("%Y-%m-%d %H:%M:%S").to_string(),
        "primaryHost": primary_host,
        "records": records,
    });

    let mut data = serde_json::to_string(&payload)?;
    // Avoid prematurely closing the inline <script> block. JSON has no literal "</",
    // so any "</" inside string values is escaped to "<\/" which is still valid JSON.
    data = data.replace("</", "<\\/");

    // Inject the snapdom library first (its own <script> block), then the JSON
    // data. The library is inserted verbatim and is NOT subject to the data escaping.
    let html = REPORT_TEMPLATE
        .replace(REPORT_SNAPDOM_PLACEHOLDER, REPORT_SNAPDOM)
        .replace(REPORT_DATA_PLACEHOLDER, &data);

    let mut file = File::create(path)
        .with_context(|| format!("failed to create HTML output {}", path.display()))?;
    file.write_all(html.as_bytes())?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{
        ContextFields, LineExtraction, UsageRecord, assign_turn_indices, collect_line_extraction,
        extract_cli_user_title_from_line, extract_custom_title, normalized_cli_title, parse_credit_details,
        project_name_from_cli_path, quick_extract_title_from_line, scan_cli_usage_connection, scan_file,
    };
    use rusqlite::Connection;
    use serde_json::json;
    use std::collections::HashMap;
    use std::fs;
    use std::path::PathBuf;

    pub(super) fn temporary_cli_root(test_name: &str) -> PathBuf {
        let unique = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let root = std::env::temp_dir().join(format!(
            "gh-usage-{test_name}-{}-{unique}",
            std::process::id()
        ));
        fs::create_dir_all(&root).unwrap();
        root
    }

    #[test]
    fn parses_credit_details_with_bullet_separator() {
        let (model, credits) = parse_credit_details("GPT-5.5 • 105.7 credits").unwrap();

        assert_eq!(model, "GPT-5.5");
        assert_eq!(credits, 105.7);
    }

    #[test]
    fn extracts_custom_title_from_chat_session_line() {
        let value = json!({"kind":1,"k":["customTitle"],"v":"Switching speed optimization notes"});

        assert_eq!(
            extract_custom_title(&value).as_deref(),
            Some("Switching speed optimization notes")
        );
    }

    #[test]
    fn quick_extracts_nested_custom_title() {
        let line = br#"{"kind":0,"v":{"version":3,"customTitle":"\u65b0\u5efaAIFriend\u76ee\u5f55\u548c\u63d2\u4ef6","title":"fallback"}}"#;
        assert_eq!(
            quick_extract_title_from_line(line).as_deref(),
            Some("\u{65b0}\u{5efa}AIFriend\u{76ee}\u{5f55}\u{548c}\u{63d2}\u{4ef6}")
        );
    }

    #[test]
    fn quick_extracts_falls_back_to_title() {
        let line = br#"{"kind":0,"v":{"title":"plain title"}}"#;
        assert_eq!(
            quick_extract_title_from_line(line).as_deref(),
            Some("plain title")
        );
    }

    #[test]
    fn quick_extracts_handles_escaped_quote() {
        let line = br#"{"customTitle":"He said \"hi\" yo"}"#;
        assert_eq!(
            quick_extract_title_from_line(line).as_deref(),
            Some("He said \"hi\" yo")
        );
    }

    #[test]
    fn extracts_copilot_cli_shutdown_model_metrics() {
        let value = json!({
            "type": "session.shutdown",
            "timestamp": "2026-05-18T10:56:39.403Z",
            "data": {
                "modelMetrics": {
                    "gpt-5.4": {
                        "requests": {"count": 1, "cost": 1},
                        "usage": {"inputTokens": 20028, "outputTokens": 62}
                    }
                }
            }
        });

        let mut extraction = LineExtraction::default();
        collect_line_extraction(&value, ContextFields::default(), &mut extraction);

        assert_eq!(extraction.records.len(), 1);
        assert_eq!(extraction.records[0].model, "gpt-5.4");
        assert_eq!(extraction.records[0].credits, 1.0);
        assert_eq!(
            extraction.records[0].context.timestamp_ms,
            Some(1779101799403)
        );
    }

    #[test]
    fn extracts_project_and_bounded_title_for_cli_sessions() {
        assert_eq!(
            project_name_from_cli_path(r"C:\work\gh-usage").as_deref(),
            Some("gh-usage")
        );
        assert_eq!(
            project_name_from_cli_path("/home/user/project/").as_deref(),
            Some("project")
        );
        assert_eq!(
            normalized_cli_title(Some("\n  Useful CLI session  \nsecond line")).as_deref(),
            Some("Useful CLI session")
        );
    }

    #[test]
    fn aggregates_cli_usage_by_session_turn_and_model() {
        let cli_root = temporary_cli_root("hybrid-cli");
        let first_events = cli_root.join("session-state/session-1/events.jsonl");
        let legacy_events = cli_root.join("session-state/session-legacy/events.jsonl");
        fs::create_dir_all(first_events.parent().unwrap()).unwrap();
        fs::create_dir_all(legacy_events.parent().unwrap()).unwrap();
        fs::write(
            &first_events,
            concat!(
                "{\"type\":\"user.message\",\"timestamp\":\"2026-08-01T00:00:09Z\",\"data\":{\"content\":\"Correct JSONL title\\nmore detail\"}}\n",
                "{\"type\":\"assistant.message\",\"timestamp\":\"2026-08-01T00:00:10.008Z\",\"data\":{\"model\":\"gpt-test\",\"apiCallId\":\"api-1\"}}\n",
                "{\"type\":\"assistant.message\",\"timestamp\":\"2026-08-01T00:00:12.010Z\",\"data\":{\"model\":\"gpt-test\",\"apiCallId\":\"api-2\"}}\n",
                "{\"type\":\"assistant.message\",\"timestamp\":\"2026-08-01T00:00:20.009Z\",\"data\":{\"model\":\"gpt-test\",\"apiCallId\":\"api-3\"}}\n"
            ),
        )
        .unwrap();
        fs::write(
            &legacy_events,
            concat!(
                "{\"type\":\"user.message\",\"timestamp\":\"2026-08-01T00:00:30Z\",\"data\":{\"content\":\"Legacy JSONL title\"}}\n",
                "{\"type\":\"session.shutdown\",\"timestamp\":\"2026-08-01T00:01:00Z\",\"data\":{\"modelMetrics\":{\"gpt-legacy\":{\"requests\":{\"cost\":1}}}}}\n"
            ),
        )
        .unwrap();
        fs::write(
            first_events.parent().unwrap().join("workspace.yaml"),
            "name: Correct CLI title property\ncwd: C:\\work\\jsonl-project\n",
        )
        .unwrap();
        fs::write(
            legacy_events.parent().unwrap().join("workspace.yaml"),
            "name: Legacy CLI title property\ncwd: C:\\work\\legacy-jsonl-project\n",
        )
        .unwrap();

        let connection = Connection::open_in_memory().unwrap();
        connection
            .execute_batch(
                "CREATE TABLE sessions (
                    id TEXT PRIMARY KEY, cwd TEXT, repository TEXT, summary TEXT
                 );
                 CREATE TABLE turns (
                    session_id TEXT, turn_index INTEGER, user_message TEXT
                 );
                 CREATE TABLE assistant_usage_events (
                    id INTEGER PRIMARY KEY, session_id TEXT, turn_index INTEGER,
                    model TEXT, total_nano_aiu INTEGER, duration_ms INTEGER,
                    created_at TEXT, agent_id TEXT
                 );
                 INSERT INTO sessions VALUES
                    ('session-1', 'C:\\work\\gh-usage', 'owner/gh-usage',
                     'Wrong SQLite title'),
                    ('session-legacy', 'C:\\work\\legacy-project', 'owner/legacy',
                     'Wrong legacy SQLite title'),
                    ('session-db-only', 'C:\\work\\db-only', 'owner/db-only',
                     'Database-only record must be ignored');
                 INSERT INTO turns VALUES ('session-1', 0, 'fallback title');
                 INSERT INTO assistant_usage_events VALUES
                    (1, 'session-1', 0, 'gpt-test', 1500000000, 2000,
                     '2026-08-01T00:00:10Z', NULL),
                    (2, 'session-1', 0, 'gpt-test', 2000000000, 1000,
                     '2026-08-01T00:00:12Z', NULL),
                    (3, 'session-1', 1, 'gpt-test', 500000000, 500,
                     '2026-08-01T00:00:20Z', NULL),
                    (4, 'session-db-only', 0, 'gpt-test', 9000000000, 500,
                     '2026-08-01T00:00:30Z', NULL);",
            )
            .unwrap();

        let result = scan_cli_usage_connection(
            &connection,
            &cli_root.join("session-store.db"),
            None,
        )
        .unwrap();

        assert_eq!(result.records.len(), 3);
        let first = &result.records[0];
        assert!((first.credits - 3.5).abs() < f64::EPSILON);
        assert_eq!(first.turn_index, Some(1));
        assert_eq!(first.session_total, Some(2));
        assert_eq!(first.duration_ms, Some(4002));
        assert_eq!(first.project.as_deref(), Some("jsonl-project"));
        assert_eq!(
            first.chat_title.as_deref(),
            Some("Correct CLI title property")
        );
        assert!(first.details.contains("2 model calls"));
        assert_eq!(first.source, "copilot.cli.events");
        assert_eq!(PathBuf::from(&first.file), first_events);
        assert_eq!(first.line, 2);

        let legacy = result
            .records
            .iter()
            .find(|record| record.session_id.as_deref() == Some("session-legacy"))
            .unwrap();
        assert_eq!(legacy.credits, 1.0);
        assert_eq!(legacy.model, "gpt-legacy");
        assert_eq!(legacy.project.as_deref(), Some("legacy-jsonl-project"));
        assert_eq!(
            legacy.chat_title.as_deref(),
            Some("Legacy CLI title property")
        );
        assert_eq!(PathBuf::from(&legacy.file), legacy_events);
        assert_eq!(legacy.line, 2);
        assert!(result
            .records
            .iter()
            .all(|record| record.session_id.as_deref() != Some("session-db-only")));

        fs::remove_dir_all(cli_root).unwrap();
    }

    #[test]
    fn extracts_only_real_root_cli_user_messages_as_titles() {
        let root = br#"{"type":"user.message","data":{"content":"JSONL title"}}"#;
        let sourced = br#"{"type":"user.message","data":{"source":"system","content":"Not a title"}}"#;
        let subagent = br#"{"type":"user.message","agentId":"agent-1","data":{"content":"Not a title"}}"#;

        assert_eq!(
            extract_cli_user_title_from_line(root).as_deref(),
            Some("JSONL title")
        );
        assert_eq!(extract_cli_user_title_from_line(sourced), None);
        assert_eq!(extract_cli_user_title_from_line(subagent), None);
    }

    #[test]
    fn scans_legacy_cli_jsonl_without_sqlite() {
        let cli_root = temporary_cli_root("legacy-jsonl-only");
        let events = cli_root.join("session-state/old-session/events.jsonl");
        fs::create_dir_all(events.parent().unwrap()).unwrap();
        fs::write(
            &events,
            concat!(
                "{\"type\":\"user.message\",\"timestamp\":\"2026-08-01T00:00:00Z\",\"data\":{\"content\":\"Old JSONL title\"}}\n",
                "{\"type\":\"session.shutdown\",\"timestamp\":\"2026-08-01T00:01:00Z\",\"data\":{\"modelMetrics\":{\"gpt-old\":{\"requests\":{\"cost\":2}}}}}\n"
            ),
        )
        .unwrap();
        fs::write(
            events.parent().unwrap().join("workspace.yaml"),
            "name: Old CLI title property\ncwd: C:\\work\\old-project\n",
        )
        .unwrap();

        let mut result = scan_file(&events, &HashMap::new());
        assign_turn_indices(&mut result.records);

        assert_eq!(result.records.len(), 1);
        let record = &result.records[0];
        assert_eq!(record.turn_index, None);
        assert_eq!(record.session_total, None);
        assert_eq!(record.session_id.as_deref(), Some("old-session"));
        assert_eq!(record.chat_title.as_deref(), Some("Old CLI title property"));
        assert_eq!(record.project.as_deref(), Some("old-project"));
        assert_eq!(record.model, "gpt-old");
        assert_eq!(record.credits, 2.0);
        assert_eq!(record.file, events.to_string_lossy());
        assert_eq!(record.line, 2);

        fs::remove_dir_all(cli_root).unwrap();
    }

    #[test]
    fn keeps_latest_vscode_result_for_each_response() {
        let root = temporary_cli_root("vscode-result-rewrites");
        let session = root.join("workspace/chatSessions/session.jsonl");
        fs::create_dir_all(session.parent().unwrap()).unwrap();
        fs::write(
            &session,
            concat!(
                "{\"kind\":1,\"k\":[\"requests\",0,\"result\"],\"v\":{\"details\":\"GPT-Test • 12.5 credits\",\"metadata\":{\"sessionId\":\"session\",\"responseId\":\"response-1\",\"modelId\":\"copilot/gpt-test\"},\"completedAt\":1000}}\n",
                "{\"kind\":1,\"k\":[\"requests\",1,\"result\"],\"v\":{\"details\":\"GPT-Test • 3 credits\",\"metadata\":{\"sessionId\":\"session\",\"responseId\":\"response-2\",\"modelId\":\"copilot/gpt-test\"},\"completedAt\":2000}}\n",
                "{\"kind\":1,\"k\":[\"requests\",0,\"result\"],\"v\":{\"details\":\"GPT-Test • 12.5 credits\",\"metadata\":{\"sessionId\":\"session\",\"responseId\":\"response-1\",\"modelId\":\"copilot/gpt-test\"},\"completedAt\":1000}}\n"
            ),
        )
        .unwrap();

        let result = scan_file(&session, &HashMap::new());

        assert_eq!(result.records.len(), 2);
        let first = result
            .records
            .iter()
            .find(|record| record.response_id.as_deref() == Some("response-1"))
            .unwrap();
        assert_eq!(first.credits, 12.5);
        assert_eq!(first.line, 3);
        assert_eq!(first.model_id.as_deref(), Some("gpt-test"));

        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn preserves_explicit_cli_turn_indices() {
        let mut records = vec![UsageRecord {
            source: "copilot.cli.sessionStore".to_owned(),
            hostname: "host".to_owned(),
            timestamp_ms: Some(1),
            local_time_hint: None,
            chat_title: None,
            model: "model".to_owned(),
            model_id: None,
            credits: 1.0,
            details: String::new(),
            session_id: Some("session".to_owned()),
            request_id: None,
            response_id: None,
            agent_id: None,
            project: None,
            duration_ms: None,
            turn_index: Some(3),
            session_total: Some(3),
            file: String::new(),
            line: 1,
        }];

        assign_turn_indices(&mut records);

        assert_eq!(records[0].turn_index, Some(3));
        assert_eq!(records[0].session_total, Some(3));
    }
}
